#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/* Auto-generated driver for `ShallowWideMLP` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * w1: shape [32768, 16384] (weight)
 * b1: shape [32768] (bias)
 * x: shape [128, 16384] (input)
 * w2: shape [32768, 32768] (weight)
 * b2: shape [32768] (bias)
 * w3: shape [16384, 32768] (weight)
 * b3: shape [16384] (bias)
 * output: shape [128, 16384]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 */
extern float *ShallowWideMLP(float *w1, float *b1, float *x, float *w2, float *b2, float *w3, float *b3);

static const size_t w1_count = 536870912;
static const size_t b1_count = 32768;
static const size_t x_count = 2097152;
static const size_t w2_count = 1073741824;
static const size_t b2_count = 32768;
static const size_t w3_count = 536870912;
static const size_t b3_count = 16384;
static const size_t OUT_COUNT = 2097152;

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *w1 = read_floats(wf, w1_count, "w1");
  float *b1 = read_floats(wf, b1_count, "b1");
  float *w2 = read_floats(wf, w2_count, "w2");
  float *b2 = read_floats(wf, b2_count, "b2");
  float *w3 = read_floats(wf, w3_count, "w3");
  float *b3 = read_floats(wf, b3_count, "b3");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  double *times = (double *)malloc(reps * sizeof(double));

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  for (int i = 0; i < 1; i++) {
    float *out = ShallowWideMLP(w1, b1, x, w2, b2, w3, b3);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    float *cur = ShallowWideMLP(w1, b1, x, w2, b2, w3, b3);
    clock_gettime(CLOCK_MONOTONIC, &t1);
    times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
               (double)(t1.tv_nsec - t0.tv_nsec);
    if (out)
      free(out);
    out = cur;
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  free(x);
  free(times);
  return 0;
}
