#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

/* Auto-generated driver for `VGG16` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * w1: shape [64, 3, 3, 3] (weight) <- features.0.weight @ byte 0
 * b1: shape [64] (bias) <- features.0.bias @ byte 6912
 * x: shape [10, 3, 224, 224] (input)
 * w2: shape [64, 64, 3, 3] (weight) <- features.2.weight @ byte 7168
 * b2: shape [64] (bias) <- features.2.bias @ byte 154624
 * w3: shape [128, 64, 3, 3] (weight) <- features.5.weight @ byte 154880
 * b3: shape [128] (bias) <- features.5.bias @ byte 449792
 * w4: shape [128, 128, 3, 3] (weight) <- features.7.weight @ byte 450304
 * b4: shape [128] (bias) <- features.7.bias @ byte 1040128
 * w5: shape [256, 128, 3, 3] (weight) <- features.10.weight @ byte 1040640
 * b5: shape [256] (bias) <- features.10.bias @ byte 2220288
 * w6: shape [256, 256, 3, 3] (weight) <- features.12.weight @ byte 2221312
 * b6: shape [256] (bias) <- features.12.bias @ byte 4580608
 * w7: shape [256, 256, 3, 3] (weight) <- features.14.weight @ byte 4581632
 * b7: shape [256] (bias) <- features.14.bias @ byte 6940928
 * w8: shape [512, 256, 3, 3] (weight) <- features.17.weight @ byte 6941952
 * b8: shape [512] (bias) <- features.17.bias @ byte 11660544
 * w9: shape [512, 512, 3, 3] (weight) <- features.19.weight @ byte 11662592
 * b9: shape [512] (bias) <- features.19.bias @ byte 21099776
 * w10: shape [512, 512, 3, 3] (weight) <- features.21.weight @ byte 21101824
 * b10: shape [512] (bias) <- features.21.bias @ byte 30539008
 * w11: shape [512, 512, 3, 3] (weight) <- features.24.weight @ byte 30541056
 * b11: shape [512] (bias) <- features.24.bias @ byte 39978240
 * w12: shape [512, 512, 3, 3] (weight) <- features.26.weight @ byte 39980288
 * b12: shape [512] (bias) <- features.26.bias @ byte 49417472
 * w13: shape [512, 512, 3, 3] (weight) <- features.28.weight @ byte 49419520
 * b13: shape [512] (bias) <- features.28.bias @ byte 58856704
 * w14: shape [4096, 25088] (weight) <- classifier.0.weight @ byte 58858752
 * b14: shape [4096] (bias) <- classifier.0.bias @ byte 469900544
 * w15: shape [4096, 4096] (weight) <- classifier.3.weight @ byte 469916928
 * b15: shape [4096] (bias) <- classifier.3.bias @ byte 537025792
 * w16: shape [1000, 4096] (weight) <- classifier.6.weight @ byte 537042176
 * b16: shape [1000] (bias) <- classifier.6.bias @ byte 553426176
 * output: shape [10, 1000]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 *
 * Usage: VGG16_driver_mim <weights> <input> <reps> <output> [run_id] [json_report]
 * run_id/json_report default to a generated UTC timestamp / a filename
 * derived from it if omitted -- pass the same run_id across every model
 * and pipeline in one batch (e.g. from reporter.py) to correlate their
 * timing reports.
 */
extern float *VGG16(float *w1, float *b1, float *x, float *w2, float *b2, float *w3, float *b3, float *w4, float *b4, float *w5, float *b5, float *w6, float *b6, float *w7, float *b7, float *w8, float *b8, float *w9, float *b9, float *w10, float *b10, float *w11, float *b11, float *w12, float *b12, float *w13, float *b13, float *w14, float *b14, float *w15, float *b15, float *w16, float *b16);

static const size_t w1_count = 1728;
static const size_t b1_count = 64;
static const size_t x_count = 1505280;
static const size_t w2_count = 36864;
static const size_t b2_count = 64;
static const size_t w3_count = 73728;
static const size_t b3_count = 128;
static const size_t w4_count = 147456;
static const size_t b4_count = 128;
static const size_t w5_count = 294912;
static const size_t b5_count = 256;
static const size_t w6_count = 589824;
static const size_t b6_count = 256;
static const size_t w7_count = 589824;
static const size_t b7_count = 256;
static const size_t w8_count = 1179648;
static const size_t b8_count = 512;
static const size_t w9_count = 2359296;
static const size_t b9_count = 512;
static const size_t w10_count = 2359296;
static const size_t b10_count = 512;
static const size_t w11_count = 2359296;
static const size_t b11_count = 512;
static const size_t w12_count = 2359296;
static const size_t b12_count = 512;
static const size_t w13_count = 2359296;
static const size_t b13_count = 512;
static const size_t w14_count = 102760448;
static const size_t b14_count = 4096;
static const size_t w15_count = 16777216;
static const size_t b15_count = 4096;
static const size_t w16_count = 4096000;
static const size_t b16_count = 1000;
static const size_t OUT_COUNT = 10000;

static float *read_floats_at(FILE *f, long byte_offset, size_t n,
                             const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  if (fseek(f, byte_offset, SEEK_SET) != 0) {
    fprintf(stderr, "seek to offset %ld for %s failed\n", byte_offset, what);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s at offset %ld: wanted %zu floats, got "
                    "%zu\n", what, byte_offset, n, got);
    exit(1);
  }
  return p;
}

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void resolve_run_id(int argc, char **argv, char *buf, size_t buflen) {
  if (argc > 5) {
    snprintf(buf, buflen, "%s", argv[5]);
    return;
  }
  time_t now = time(NULL);
  struct tm tm_utc;
  gmtime_r(&now, &tm_utc);
  strftime(buf, buflen, "%Y%m%d_%H%M%S", &tm_utc);
}

static void print_json_string(FILE *f, const char *s) {
  fputc('"', f);
  for (const char *p = s; *p; p++) {
    if (*p == '"' || *p == '\\')
      fputc('\\', f);
    fputc(*p, f);
  }
  fputc('"', f);
}

static void write_timing_report(const char *json_path, const char *model,
                                 const char *pipeline, const char *run_id,
                                 const char *weights_path, const char *input_path,
                                 const char *output_path, int reps,
                                 double median_ns, double mean_ns, double min_ns,
                                 double max_ns) {
  FILE *jf = fopen(json_path, "w");
  if (!jf) {
    fprintf(stderr, "warning: failed to write timing report '%s': ", json_path);
    perror(NULL);
    return;
  }
  fprintf(jf, "{\n  \"model\": ");
  print_json_string(jf, model);
  fprintf(jf, ",\n  \"pipeline\": ");
  print_json_string(jf, pipeline);
  fprintf(jf, ",\n  \"run_id\": ");
  print_json_string(jf, run_id);
  fprintf(jf, ",\n  \"weights_path\": ");
  print_json_string(jf, weights_path);
  fprintf(jf, ",\n  \"input_path\": ");
  print_json_string(jf, input_path);
  fprintf(jf, ",\n  \"output_path\": ");
  print_json_string(jf, output_path);
  fprintf(jf, ",\n  \"reps\": %d", reps);
  fprintf(jf, ",\n  \"median_ns\": %.1f", median_ns);
  fprintf(jf, ",\n  \"mean_ns\": %.1f", mean_ns);
  fprintf(jf, ",\n  \"min_ns\": %.1f", min_ns);
  fprintf(jf, ",\n  \"max_ns\": %.1f", max_ns);
  fprintf(jf, "\n}\n");
  fclose(jf);
  printf("wrote timing report to %s\n", json_path);
  fflush(stdout);
}

/* --- per-call process isolation; see c_fork_helpers() in gen_drivers.py ---
 * Each call to the model runs in a forked child, so the leak of its
 * internal intermediates cannot accumulate across reps. Weights and input
 * are inherited copy-on-write and are NOT duplicated. Elapsed times come
 * back through a shared anonymous mapping, and the final rep's child writes
 * the output file itself so the result never has to cross the process
 * boundary.
 *
 * Set DRIVER_NO_FORK=1 to run every call in-process instead -- the previous
 * behaviour, for A/B or for profilers that dislike fork.
 */
static int driver_fork_enabled(void) {
  const char *e = getenv("DRIVER_NO_FORK");
  return !(e && e[0] && e[0] != '0');
}

static double *alloc_shared_times(int reps) {
  size_t n = (size_t)reps * sizeof(double);
  void *p = mmap(NULL, n, PROT_READ | PROT_WRITE,
                 MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  if (p == MAP_FAILED) {
    perror("mmap for shared timing buffer");
    exit(1);
  }
  return (double *)p;
}

static void await_child(pid_t pid, const char *what) {
  int st = 0;
  if (waitpid(pid, &st, 0) < 0) {
    perror("waitpid");
    exit(1);
  }
  if (WIFSIGNALED(st)) {
    int s = WTERMSIG(st);
    fprintf(stderr, "%s: child killed by signal %d\n", what, s);
    if (s == SIGKILL)
      fprintf(stderr,
              "  SIGKILL almost always means the OOM killer. This model "
              "leaks several GiB\n  per call inside the generated code; a "
              "single call already exceeds free RAM.\n  Forking bounds the "
              "leak to one call, so it cannot help beyond that.\n");
    exit(1);
  }
  if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
    fprintf(stderr, "%s: child exited with status %d\n", what,
            WIFEXITED(st) ? WEXITSTATUS(st) : -1);
    exit(1);
  }
}

static void release_times(double *times, int reps, int forked) {
  if (forked)
    munmap(times, (size_t)reps * sizeof(double));
  else
    free(times);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  char run_id_buf[64];
  resolve_run_id(argc, argv, run_id_buf, sizeof(run_id_buf));
  const char *run_id = run_id_buf;

  char json_path_buf[512];
  const char *json_report_path;
  if (argc > 6) {
    json_report_path = argv[6];
  } else {
    snprintf(json_path_buf, sizeof(json_path_buf), "VGG16_mim_llvm_%s_timing.json", run_id);
    json_report_path = json_path_buf;
  }

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *w1 = read_floats_at(wf, 0, w1_count, "w1");
  float *b1 = read_floats_at(wf, 6912, b1_count, "b1");
  float *w2 = read_floats_at(wf, 7168, w2_count, "w2");
  float *b2 = read_floats_at(wf, 154624, b2_count, "b2");
  float *w3 = read_floats_at(wf, 154880, w3_count, "w3");
  float *b3 = read_floats_at(wf, 449792, b3_count, "b3");
  float *w4 = read_floats_at(wf, 450304, w4_count, "w4");
  float *b4 = read_floats_at(wf, 1040128, b4_count, "b4");
  float *w5 = read_floats_at(wf, 1040640, w5_count, "w5");
  float *b5 = read_floats_at(wf, 2220288, b5_count, "b5");
  float *w6 = read_floats_at(wf, 2221312, w6_count, "w6");
  float *b6 = read_floats_at(wf, 4580608, b6_count, "b6");
  float *w7 = read_floats_at(wf, 4581632, w7_count, "w7");
  float *b7 = read_floats_at(wf, 6940928, b7_count, "b7");
  float *w8 = read_floats_at(wf, 6941952, w8_count, "w8");
  float *b8 = read_floats_at(wf, 11660544, b8_count, "b8");
  float *w9 = read_floats_at(wf, 11662592, w9_count, "w9");
  float *b9 = read_floats_at(wf, 21099776, b9_count, "b9");
  float *w10 = read_floats_at(wf, 21101824, w10_count, "w10");
  float *b10 = read_floats_at(wf, 30539008, b10_count, "b10");
  float *w11 = read_floats_at(wf, 30541056, w11_count, "w11");
  float *b11 = read_floats_at(wf, 39978240, b11_count, "b11");
  float *w12 = read_floats_at(wf, 39980288, w12_count, "w12");
  float *b12 = read_floats_at(wf, 49417472, b12_count, "b12");
  float *w13 = read_floats_at(wf, 49419520, w13_count, "w13");
  float *b13 = read_floats_at(wf, 58856704, b13_count, "b13");
  float *w14 = read_floats_at(wf, 58858752, w14_count, "w14");
  float *b14 = read_floats_at(wf, 469900544, b14_count, "b14");
  float *w15 = read_floats_at(wf, 469916928, w15_count, "w15");
  float *b15 = read_floats_at(wf, 537025792, b15_count, "b15");
  float *w16 = read_floats_at(wf, 537042176, w16_count, "w16");
  float *b16 = read_floats_at(wf, 553426176, b16_count, "b16");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  const int use_fork = driver_fork_enabled();
  double *times = use_fork ? alloc_shared_times(reps)
                           : (double *)malloc(reps * sizeof(double));
  printf("call isolation: %s\n", use_fork ? "fork per call" : "in-process (DRIVER_NO_FORK)");

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  if (use_fork) {
    fflush(NULL);
    pid_t p = fork();
    if (p < 0) { perror("fork"); return 1; }
    if (p == 0) {
      float *out = VGG16(w1, b1, x, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16);
      free(out);
      _exit(0);
    }
    await_child(p, "warm-up");
  } else {
    float *out = VGG16(w1, b1, x, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    const int is_last = (i == reps - 1);
    if (use_fork) {
      fflush(NULL);
      pid_t p = fork();
      if (p < 0) { perror("fork"); return 1; }
      if (p == 0) {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        float *cur = VGG16(w1, b1, x, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                   (double)(t1.tv_nsec - t0.tv_nsec);
        /* The last rep's child owns writing the result -- that keeps the
           output buffer from having to cross the process boundary.
           write_result() frees `cur`. */
        if (is_last)
          write_result(cur, output_path);
        _exit(0);
      }
      await_child(p, "timed rep");
    } else {
      struct timespec t0, t1;
      clock_gettime(CLOCK_MONOTONIC, &t0);
      float *cur = VGG16(w1, b1, x, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16);
      clock_gettime(CLOCK_MONOTONIC, &t1);
      times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                 (double)(t1.tv_nsec - t0.tv_nsec);
      if (out)
        free(out);
      out = cur;
    }
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  if (!use_fork)
    write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  write_timing_report(json_report_path, "VGG16", "mim_llvm", run_id,
                       weights_path, input_path, output_path, reps,
                       times[reps / 2], sum / reps, times[0], times[reps - 1]);

  free(x);
  release_times(times, reps, use_fork);
  return 0;
}
