#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

/* Auto-generated driver for `MobileNetV1` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * w1: shape [32, 3, 3, 3] (weight) <- model.0.0.weight @ byte 0
 * x: shape [10, 3, 224, 224] (input)
 * b1: shape [32] (bias) <- model.0.1.running_mean @ byte 3456
 * b2: shape [32] (bias) <- model.0.1.running_var @ byte 3584
 * b3: shape [32] (bias) <- model.0.1.weight @ byte 3712
 * b4: shape [32] (bias) <- model.0.1.bias @ byte 3840
 * w2: shape [32, 3, 3] (weight) <- model.1.0.weight @ byte 3968
 * b5: shape [32] (bias) <- model.1.1.running_mean @ byte 5120
 * b6: shape [32] (bias) <- model.1.1.running_var @ byte 5248
 * b7: shape [32] (bias) <- model.1.1.weight @ byte 5376
 * b8: shape [32] (bias) <- model.1.1.bias @ byte 5504
 * w3: shape [64, 32] (weight) <- model.1.3.weight @ byte 5632
 * b9: shape [64] (bias) <- model.1.4.running_mean @ byte 13824
 * b10: shape [64] (bias) <- model.1.4.running_var @ byte 14080
 * b11: shape [64] (bias) <- model.1.4.weight @ byte 14336
 * b12: shape [64] (bias) <- model.1.4.bias @ byte 14592
 * w4: shape [64, 3, 3] (weight) <- model.2.0.weight @ byte 14848
 * b13: shape [64] (bias) <- model.2.1.running_mean @ byte 17152
 * b14: shape [64] (bias) <- model.2.1.running_var @ byte 17408
 * b15: shape [64] (bias) <- model.2.1.weight @ byte 17664
 * b16: shape [64] (bias) <- model.2.1.bias @ byte 17920
 * w5: shape [128, 64] (weight) <- model.2.3.weight @ byte 18176
 * b17: shape [128] (bias) <- model.2.4.running_mean @ byte 50944
 * b18: shape [128] (bias) <- model.2.4.running_var @ byte 51456
 * b19: shape [128] (bias) <- model.2.4.weight @ byte 51968
 * b20: shape [128] (bias) <- model.2.4.bias @ byte 52480
 * w6: shape [128, 3, 3] (weight) <- model.3.0.weight @ byte 52992
 * b21: shape [128] (bias) <- model.3.1.running_mean @ byte 57600
 * b22: shape [128] (bias) <- model.3.1.running_var @ byte 58112
 * b23: shape [128] (bias) <- model.3.1.weight @ byte 58624
 * b24: shape [128] (bias) <- model.3.1.bias @ byte 59136
 * w7: shape [128, 128] (weight) <- model.3.3.weight @ byte 59648
 * b25: shape [128] (bias) <- model.3.4.running_mean @ byte 125184
 * b26: shape [128] (bias) <- model.3.4.running_var @ byte 125696
 * b27: shape [128] (bias) <- model.3.4.weight @ byte 126208
 * b28: shape [128] (bias) <- model.3.4.bias @ byte 126720
 * w8: shape [128, 3, 3] (weight) <- model.4.0.weight @ byte 127232
 * b29: shape [128] (bias) <- model.4.1.running_mean @ byte 131840
 * b30: shape [128] (bias) <- model.4.1.running_var @ byte 132352
 * b31: shape [128] (bias) <- model.4.1.weight @ byte 132864
 * b32: shape [128] (bias) <- model.4.1.bias @ byte 133376
 * w9: shape [256, 128] (weight) <- model.4.3.weight @ byte 133888
 * b33: shape [256] (bias) <- model.4.4.running_mean @ byte 264960
 * b34: shape [256] (bias) <- model.4.4.running_var @ byte 265984
 * b35: shape [256] (bias) <- model.4.4.weight @ byte 267008
 * b36: shape [256] (bias) <- model.4.4.bias @ byte 268032
 * w10: shape [256, 3, 3] (weight) <- model.5.0.weight @ byte 269056
 * b37: shape [256] (bias) <- model.5.1.running_mean @ byte 278272
 * b38: shape [256] (bias) <- model.5.1.running_var @ byte 279296
 * b39: shape [256] (bias) <- model.5.1.weight @ byte 280320
 * b40: shape [256] (bias) <- model.5.1.bias @ byte 281344
 * w11: shape [256, 256] (weight) <- model.5.3.weight @ byte 282368
 * b41: shape [256] (bias) <- model.5.4.running_mean @ byte 544512
 * b42: shape [256] (bias) <- model.5.4.running_var @ byte 545536
 * b43: shape [256] (bias) <- model.5.4.weight @ byte 546560
 * b44: shape [256] (bias) <- model.5.4.bias @ byte 547584
 * w12: shape [256, 3, 3] (weight) <- model.6.0.weight @ byte 548608
 * b45: shape [256] (bias) <- model.6.1.running_mean @ byte 557824
 * b46: shape [256] (bias) <- model.6.1.running_var @ byte 558848
 * b47: shape [256] (bias) <- model.6.1.weight @ byte 559872
 * b48: shape [256] (bias) <- model.6.1.bias @ byte 560896
 * w13: shape [512, 256] (weight) <- model.6.3.weight @ byte 561920
 * b49: shape [512] (bias) <- model.6.4.running_mean @ byte 1086208
 * b50: shape [512] (bias) <- model.6.4.running_var @ byte 1088256
 * b51: shape [512] (bias) <- model.6.4.weight @ byte 1090304
 * b52: shape [512] (bias) <- model.6.4.bias @ byte 1092352
 * w14: shape [512, 3, 3] (weight) <- model.7.0.weight @ byte 1094400
 * b53: shape [512] (bias) <- model.7.1.running_mean @ byte 1112832
 * b54: shape [512] (bias) <- model.7.1.running_var @ byte 1114880
 * b55: shape [512] (bias) <- model.7.1.weight @ byte 1116928
 * b56: shape [512] (bias) <- model.7.1.bias @ byte 1118976
 * w15: shape [512, 512] (weight) <- model.7.3.weight @ byte 1121024
 * b57: shape [512] (bias) <- model.7.4.running_mean @ byte 2169600
 * b58: shape [512] (bias) <- model.7.4.running_var @ byte 2171648
 * b59: shape [512] (bias) <- model.7.4.weight @ byte 2173696
 * b60: shape [512] (bias) <- model.7.4.bias @ byte 2175744
 * w16: shape [512, 3, 3] (weight) <- model.8.0.weight @ byte 2177792
 * b61: shape [512] (bias) <- model.8.1.running_mean @ byte 2196224
 * b62: shape [512] (bias) <- model.8.1.running_var @ byte 2198272
 * b63: shape [512] (bias) <- model.8.1.weight @ byte 2200320
 * b64: shape [512] (bias) <- model.8.1.bias @ byte 2202368
 * w17: shape [512, 512] (weight) <- model.8.3.weight @ byte 2204416
 * b65: shape [512] (bias) <- model.8.4.running_mean @ byte 3252992
 * b66: shape [512] (bias) <- model.8.4.running_var @ byte 3255040
 * b67: shape [512] (bias) <- model.8.4.weight @ byte 3257088
 * b68: shape [512] (bias) <- model.8.4.bias @ byte 3259136
 * w18: shape [512, 3, 3] (weight) <- model.9.0.weight @ byte 3261184
 * b69: shape [512] (bias) <- model.9.1.running_mean @ byte 3279616
 * b70: shape [512] (bias) <- model.9.1.running_var @ byte 3281664
 * b71: shape [512] (bias) <- model.9.1.weight @ byte 3283712
 * b72: shape [512] (bias) <- model.9.1.bias @ byte 3285760
 * w19: shape [512, 512] (weight) <- model.9.3.weight @ byte 3287808
 * b73: shape [512] (bias) <- model.9.4.running_mean @ byte 4336384
 * b74: shape [512] (bias) <- model.9.4.running_var @ byte 4338432
 * b75: shape [512] (bias) <- model.9.4.weight @ byte 4340480
 * b76: shape [512] (bias) <- model.9.4.bias @ byte 4342528
 * w20: shape [512, 3, 3] (weight) <- model.10.0.weight @ byte 4344576
 * b77: shape [512] (bias) <- model.10.1.running_mean @ byte 4363008
 * b78: shape [512] (bias) <- model.10.1.running_var @ byte 4365056
 * b79: shape [512] (bias) <- model.10.1.weight @ byte 4367104
 * b80: shape [512] (bias) <- model.10.1.bias @ byte 4369152
 * w21: shape [512, 512] (weight) <- model.10.3.weight @ byte 4371200
 * b81: shape [512] (bias) <- model.10.4.running_mean @ byte 5419776
 * b82: shape [512] (bias) <- model.10.4.running_var @ byte 5421824
 * b83: shape [512] (bias) <- model.10.4.weight @ byte 5423872
 * b84: shape [512] (bias) <- model.10.4.bias @ byte 5425920
 * w22: shape [512, 3, 3] (weight) <- model.11.0.weight @ byte 5427968
 * b85: shape [512] (bias) <- model.11.1.running_mean @ byte 5446400
 * b86: shape [512] (bias) <- model.11.1.running_var @ byte 5448448
 * b87: shape [512] (bias) <- model.11.1.weight @ byte 5450496
 * b88: shape [512] (bias) <- model.11.1.bias @ byte 5452544
 * w23: shape [512, 512] (weight) <- model.11.3.weight @ byte 5454592
 * b89: shape [512] (bias) <- model.11.4.running_mean @ byte 6503168
 * b90: shape [512] (bias) <- model.11.4.running_var @ byte 6505216
 * b91: shape [512] (bias) <- model.11.4.weight @ byte 6507264
 * b92: shape [512] (bias) <- model.11.4.bias @ byte 6509312
 * w24: shape [512, 3, 3] (weight) <- model.12.0.weight @ byte 6511360
 * b93: shape [512] (bias) <- model.12.1.running_mean @ byte 6529792
 * b94: shape [512] (bias) <- model.12.1.running_var @ byte 6531840
 * b95: shape [512] (bias) <- model.12.1.weight @ byte 6533888
 * b96: shape [512] (bias) <- model.12.1.bias @ byte 6535936
 * w25: shape [1024, 512] (weight) <- model.12.3.weight @ byte 6537984
 * b97: shape [1024] (bias) <- model.12.4.running_mean @ byte 8635136
 * b98: shape [1024] (bias) <- model.12.4.running_var @ byte 8639232
 * b99: shape [1024] (bias) <- model.12.4.weight @ byte 8643328
 * b100: shape [1024] (bias) <- model.12.4.bias @ byte 8647424
 * w26: shape [1024, 3, 3] (weight) <- model.13.0.weight @ byte 8651520
 * b101: shape [1024] (bias) <- model.13.1.running_mean @ byte 8688384
 * b102: shape [1024] (bias) <- model.13.1.running_var @ byte 8692480
 * b103: shape [1024] (bias) <- model.13.1.weight @ byte 8696576
 * b104: shape [1024] (bias) <- model.13.1.bias @ byte 8700672
 * w27: shape [1024, 1024] (weight) <- model.13.3.weight @ byte 8704768
 * b105: shape [1024] (bias) <- model.13.4.running_mean @ byte 12899072
 * b106: shape [1024] (bias) <- model.13.4.running_var @ byte 12903168
 * b107: shape [1024] (bias) <- model.13.4.weight @ byte 12907264
 * b108: shape [1024] (bias) <- model.13.4.bias @ byte 12911360
 * w28: shape [1000, 1024] (weight) <- fc.weight @ byte 12915456
 * b109: shape [1000] (bias) <- fc.bias @ byte 17011456
 * output: shape [10, 1000]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 *
 * Usage: MobileNetV1_driver_mim <weights> <input> <reps> <output> [run_id] [json_report]
 * run_id/json_report default to a generated UTC timestamp / a filename
 * derived from it if omitted -- pass the same run_id across every model
 * and pipeline in one batch (e.g. from reporter.py) to correlate their
 * timing reports.
 */
extern float *MobileNetV1(float *w1, float *x, float *b1, float *b2, float *b3, float *b4, float *w2, float *b5, float *b6, float *b7, float *b8, float *w3, float *b9, float *b10, float *b11, float *b12, float *w4, float *b13, float *b14, float *b15, float *b16, float *w5, float *b17, float *b18, float *b19, float *b20, float *w6, float *b21, float *b22, float *b23, float *b24, float *w7, float *b25, float *b26, float *b27, float *b28, float *w8, float *b29, float *b30, float *b31, float *b32, float *w9, float *b33, float *b34, float *b35, float *b36, float *w10, float *b37, float *b38, float *b39, float *b40, float *w11, float *b41, float *b42, float *b43, float *b44, float *w12, float *b45, float *b46, float *b47, float *b48, float *w13, float *b49, float *b50, float *b51, float *b52, float *w14, float *b53, float *b54, float *b55, float *b56, float *w15, float *b57, float *b58, float *b59, float *b60, float *w16, float *b61, float *b62, float *b63, float *b64, float *w17, float *b65, float *b66, float *b67, float *b68, float *w18, float *b69, float *b70, float *b71, float *b72, float *w19, float *b73, float *b74, float *b75, float *b76, float *w20, float *b77, float *b78, float *b79, float *b80, float *w21, float *b81, float *b82, float *b83, float *b84, float *w22, float *b85, float *b86, float *b87, float *b88, float *w23, float *b89, float *b90, float *b91, float *b92, float *w24, float *b93, float *b94, float *b95, float *b96, float *w25, float *b97, float *b98, float *b99, float *b100, float *w26, float *b101, float *b102, float *b103, float *b104, float *w27, float *b105, float *b106, float *b107, float *b108, float *w28, float *b109);

static const size_t w1_count = 864;
static const size_t x_count = 1505280;
static const size_t b1_count = 32;
static const size_t b2_count = 32;
static const size_t b3_count = 32;
static const size_t b4_count = 32;
static const size_t w2_count = 288;
static const size_t b5_count = 32;
static const size_t b6_count = 32;
static const size_t b7_count = 32;
static const size_t b8_count = 32;
static const size_t w3_count = 2048;
static const size_t b9_count = 64;
static const size_t b10_count = 64;
static const size_t b11_count = 64;
static const size_t b12_count = 64;
static const size_t w4_count = 576;
static const size_t b13_count = 64;
static const size_t b14_count = 64;
static const size_t b15_count = 64;
static const size_t b16_count = 64;
static const size_t w5_count = 8192;
static const size_t b17_count = 128;
static const size_t b18_count = 128;
static const size_t b19_count = 128;
static const size_t b20_count = 128;
static const size_t w6_count = 1152;
static const size_t b21_count = 128;
static const size_t b22_count = 128;
static const size_t b23_count = 128;
static const size_t b24_count = 128;
static const size_t w7_count = 16384;
static const size_t b25_count = 128;
static const size_t b26_count = 128;
static const size_t b27_count = 128;
static const size_t b28_count = 128;
static const size_t w8_count = 1152;
static const size_t b29_count = 128;
static const size_t b30_count = 128;
static const size_t b31_count = 128;
static const size_t b32_count = 128;
static const size_t w9_count = 32768;
static const size_t b33_count = 256;
static const size_t b34_count = 256;
static const size_t b35_count = 256;
static const size_t b36_count = 256;
static const size_t w10_count = 2304;
static const size_t b37_count = 256;
static const size_t b38_count = 256;
static const size_t b39_count = 256;
static const size_t b40_count = 256;
static const size_t w11_count = 65536;
static const size_t b41_count = 256;
static const size_t b42_count = 256;
static const size_t b43_count = 256;
static const size_t b44_count = 256;
static const size_t w12_count = 2304;
static const size_t b45_count = 256;
static const size_t b46_count = 256;
static const size_t b47_count = 256;
static const size_t b48_count = 256;
static const size_t w13_count = 131072;
static const size_t b49_count = 512;
static const size_t b50_count = 512;
static const size_t b51_count = 512;
static const size_t b52_count = 512;
static const size_t w14_count = 4608;
static const size_t b53_count = 512;
static const size_t b54_count = 512;
static const size_t b55_count = 512;
static const size_t b56_count = 512;
static const size_t w15_count = 262144;
static const size_t b57_count = 512;
static const size_t b58_count = 512;
static const size_t b59_count = 512;
static const size_t b60_count = 512;
static const size_t w16_count = 4608;
static const size_t b61_count = 512;
static const size_t b62_count = 512;
static const size_t b63_count = 512;
static const size_t b64_count = 512;
static const size_t w17_count = 262144;
static const size_t b65_count = 512;
static const size_t b66_count = 512;
static const size_t b67_count = 512;
static const size_t b68_count = 512;
static const size_t w18_count = 4608;
static const size_t b69_count = 512;
static const size_t b70_count = 512;
static const size_t b71_count = 512;
static const size_t b72_count = 512;
static const size_t w19_count = 262144;
static const size_t b73_count = 512;
static const size_t b74_count = 512;
static const size_t b75_count = 512;
static const size_t b76_count = 512;
static const size_t w20_count = 4608;
static const size_t b77_count = 512;
static const size_t b78_count = 512;
static const size_t b79_count = 512;
static const size_t b80_count = 512;
static const size_t w21_count = 262144;
static const size_t b81_count = 512;
static const size_t b82_count = 512;
static const size_t b83_count = 512;
static const size_t b84_count = 512;
static const size_t w22_count = 4608;
static const size_t b85_count = 512;
static const size_t b86_count = 512;
static const size_t b87_count = 512;
static const size_t b88_count = 512;
static const size_t w23_count = 262144;
static const size_t b89_count = 512;
static const size_t b90_count = 512;
static const size_t b91_count = 512;
static const size_t b92_count = 512;
static const size_t w24_count = 4608;
static const size_t b93_count = 512;
static const size_t b94_count = 512;
static const size_t b95_count = 512;
static const size_t b96_count = 512;
static const size_t w25_count = 524288;
static const size_t b97_count = 1024;
static const size_t b98_count = 1024;
static const size_t b99_count = 1024;
static const size_t b100_count = 1024;
static const size_t w26_count = 9216;
static const size_t b101_count = 1024;
static const size_t b102_count = 1024;
static const size_t b103_count = 1024;
static const size_t b104_count = 1024;
static const size_t w27_count = 1048576;
static const size_t b105_count = 1024;
static const size_t b106_count = 1024;
static const size_t b107_count = 1024;
static const size_t b108_count = 1024;
static const size_t w28_count = 1024000;
static const size_t b109_count = 1000;
static const size_t OUT_COUNT = 10000;

static float *read_floats_at(FILE *f, long byte_offset, size_t n,
                             const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  if (fseek(f, byte_offset, SEEK_SET) != 0) {
    fprintf(stderr, "seek to offset %ld for %s failed\n", byte_offset, what);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s at offset %ld: wanted %zu floats, got "
                    "%zu\n", what, byte_offset, n, got);
    exit(1);
  }
  return p;
}

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void resolve_run_id(int argc, char **argv, char *buf, size_t buflen) {
  if (argc > 5) {
    snprintf(buf, buflen, "%s", argv[5]);
    return;
  }
  time_t now = time(NULL);
  struct tm tm_utc;
  gmtime_r(&now, &tm_utc);
  strftime(buf, buflen, "%Y%m%d_%H%M%S", &tm_utc);
}

static void print_json_string(FILE *f, const char *s) {
  fputc('"', f);
  for (const char *p = s; *p; p++) {
    if (*p == '"' || *p == '\\')
      fputc('\\', f);
    fputc(*p, f);
  }
  fputc('"', f);
}

static void write_timing_report(const char *json_path, const char *model,
                                 const char *pipeline, const char *run_id,
                                 const char *weights_path, const char *input_path,
                                 const char *output_path, int reps,
                                 double median_ns, double mean_ns, double min_ns,
                                 double max_ns) {
  FILE *jf = fopen(json_path, "w");
  if (!jf) {
    fprintf(stderr, "warning: failed to write timing report '%s': ", json_path);
    perror(NULL);
    return;
  }
  fprintf(jf, "{\n  \"model\": ");
  print_json_string(jf, model);
  fprintf(jf, ",\n  \"pipeline\": ");
  print_json_string(jf, pipeline);
  fprintf(jf, ",\n  \"run_id\": ");
  print_json_string(jf, run_id);
  fprintf(jf, ",\n  \"weights_path\": ");
  print_json_string(jf, weights_path);
  fprintf(jf, ",\n  \"input_path\": ");
  print_json_string(jf, input_path);
  fprintf(jf, ",\n  \"output_path\": ");
  print_json_string(jf, output_path);
  fprintf(jf, ",\n  \"reps\": %d", reps);
  fprintf(jf, ",\n  \"median_ns\": %.1f", median_ns);
  fprintf(jf, ",\n  \"mean_ns\": %.1f", mean_ns);
  fprintf(jf, ",\n  \"min_ns\": %.1f", min_ns);
  fprintf(jf, ",\n  \"max_ns\": %.1f", max_ns);
  fprintf(jf, "\n}\n");
  fclose(jf);
  printf("wrote timing report to %s\n", json_path);
  fflush(stdout);
}

/* --- per-call process isolation; see c_fork_helpers() in gen_drivers.py ---
 * Each call to the model runs in a forked child, so the leak of its
 * internal intermediates cannot accumulate across reps. Weights and input
 * are inherited copy-on-write and are NOT duplicated. Elapsed times come
 * back through a shared anonymous mapping, and the final rep's child writes
 * the output file itself so the result never has to cross the process
 * boundary.
 *
 * Set DRIVER_NO_FORK=1 to run every call in-process instead -- the previous
 * behaviour, for A/B or for profilers that dislike fork.
 */
static int driver_fork_enabled(void) {
  const char *e = getenv("DRIVER_NO_FORK");
  return !(e && e[0] && e[0] != '0');
}

static double *alloc_shared_times(int reps) {
  size_t n = (size_t)reps * sizeof(double);
  void *p = mmap(NULL, n, PROT_READ | PROT_WRITE,
                 MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  if (p == MAP_FAILED) {
    perror("mmap for shared timing buffer");
    exit(1);
  }
  return (double *)p;
}

static void await_child(pid_t pid, const char *what) {
  int st = 0;
  if (waitpid(pid, &st, 0) < 0) {
    perror("waitpid");
    exit(1);
  }
  if (WIFSIGNALED(st)) {
    int s = WTERMSIG(st);
    fprintf(stderr, "%s: child killed by signal %d\n", what, s);
    if (s == SIGKILL)
      fprintf(stderr,
              "  SIGKILL almost always means the OOM killer. This model "
              "leaks several GiB\n  per call inside the generated code; a "
              "single call already exceeds free RAM.\n  Forking bounds the "
              "leak to one call, so it cannot help beyond that.\n");
    exit(1);
  }
  if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
    fprintf(stderr, "%s: child exited with status %d\n", what,
            WIFEXITED(st) ? WEXITSTATUS(st) : -1);
    exit(1);
  }
}

static void release_times(double *times, int reps, int forked) {
  if (forked)
    munmap(times, (size_t)reps * sizeof(double));
  else
    free(times);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  char run_id_buf[64];
  resolve_run_id(argc, argv, run_id_buf, sizeof(run_id_buf));
  const char *run_id = run_id_buf;

  char json_path_buf[512];
  const char *json_report_path;
  if (argc > 6) {
    json_report_path = argv[6];
  } else {
    snprintf(json_path_buf, sizeof(json_path_buf), "MobileNetV1_mim_llvm_%s_timing.json", run_id);
    json_report_path = json_path_buf;
  }

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *w1 = read_floats_at(wf, 0, w1_count, "w1");
  float *b1 = read_floats_at(wf, 3456, b1_count, "b1");
  float *b2 = read_floats_at(wf, 3584, b2_count, "b2");
  float *b3 = read_floats_at(wf, 3712, b3_count, "b3");
  float *b4 = read_floats_at(wf, 3840, b4_count, "b4");
  float *w2 = read_floats_at(wf, 3968, w2_count, "w2");
  float *b5 = read_floats_at(wf, 5120, b5_count, "b5");
  float *b6 = read_floats_at(wf, 5248, b6_count, "b6");
  float *b7 = read_floats_at(wf, 5376, b7_count, "b7");
  float *b8 = read_floats_at(wf, 5504, b8_count, "b8");
  float *w3 = read_floats_at(wf, 5632, w3_count, "w3");
  float *b9 = read_floats_at(wf, 13824, b9_count, "b9");
  float *b10 = read_floats_at(wf, 14080, b10_count, "b10");
  float *b11 = read_floats_at(wf, 14336, b11_count, "b11");
  float *b12 = read_floats_at(wf, 14592, b12_count, "b12");
  float *w4 = read_floats_at(wf, 14848, w4_count, "w4");
  float *b13 = read_floats_at(wf, 17152, b13_count, "b13");
  float *b14 = read_floats_at(wf, 17408, b14_count, "b14");
  float *b15 = read_floats_at(wf, 17664, b15_count, "b15");
  float *b16 = read_floats_at(wf, 17920, b16_count, "b16");
  float *w5 = read_floats_at(wf, 18176, w5_count, "w5");
  float *b17 = read_floats_at(wf, 50944, b17_count, "b17");
  float *b18 = read_floats_at(wf, 51456, b18_count, "b18");
  float *b19 = read_floats_at(wf, 51968, b19_count, "b19");
  float *b20 = read_floats_at(wf, 52480, b20_count, "b20");
  float *w6 = read_floats_at(wf, 52992, w6_count, "w6");
  float *b21 = read_floats_at(wf, 57600, b21_count, "b21");
  float *b22 = read_floats_at(wf, 58112, b22_count, "b22");
  float *b23 = read_floats_at(wf, 58624, b23_count, "b23");
  float *b24 = read_floats_at(wf, 59136, b24_count, "b24");
  float *w7 = read_floats_at(wf, 59648, w7_count, "w7");
  float *b25 = read_floats_at(wf, 125184, b25_count, "b25");
  float *b26 = read_floats_at(wf, 125696, b26_count, "b26");
  float *b27 = read_floats_at(wf, 126208, b27_count, "b27");
  float *b28 = read_floats_at(wf, 126720, b28_count, "b28");
  float *w8 = read_floats_at(wf, 127232, w8_count, "w8");
  float *b29 = read_floats_at(wf, 131840, b29_count, "b29");
  float *b30 = read_floats_at(wf, 132352, b30_count, "b30");
  float *b31 = read_floats_at(wf, 132864, b31_count, "b31");
  float *b32 = read_floats_at(wf, 133376, b32_count, "b32");
  float *w9 = read_floats_at(wf, 133888, w9_count, "w9");
  float *b33 = read_floats_at(wf, 264960, b33_count, "b33");
  float *b34 = read_floats_at(wf, 265984, b34_count, "b34");
  float *b35 = read_floats_at(wf, 267008, b35_count, "b35");
  float *b36 = read_floats_at(wf, 268032, b36_count, "b36");
  float *w10 = read_floats_at(wf, 269056, w10_count, "w10");
  float *b37 = read_floats_at(wf, 278272, b37_count, "b37");
  float *b38 = read_floats_at(wf, 279296, b38_count, "b38");
  float *b39 = read_floats_at(wf, 280320, b39_count, "b39");
  float *b40 = read_floats_at(wf, 281344, b40_count, "b40");
  float *w11 = read_floats_at(wf, 282368, w11_count, "w11");
  float *b41 = read_floats_at(wf, 544512, b41_count, "b41");
  float *b42 = read_floats_at(wf, 545536, b42_count, "b42");
  float *b43 = read_floats_at(wf, 546560, b43_count, "b43");
  float *b44 = read_floats_at(wf, 547584, b44_count, "b44");
  float *w12 = read_floats_at(wf, 548608, w12_count, "w12");
  float *b45 = read_floats_at(wf, 557824, b45_count, "b45");
  float *b46 = read_floats_at(wf, 558848, b46_count, "b46");
  float *b47 = read_floats_at(wf, 559872, b47_count, "b47");
  float *b48 = read_floats_at(wf, 560896, b48_count, "b48");
  float *w13 = read_floats_at(wf, 561920, w13_count, "w13");
  float *b49 = read_floats_at(wf, 1086208, b49_count, "b49");
  float *b50 = read_floats_at(wf, 1088256, b50_count, "b50");
  float *b51 = read_floats_at(wf, 1090304, b51_count, "b51");
  float *b52 = read_floats_at(wf, 1092352, b52_count, "b52");
  float *w14 = read_floats_at(wf, 1094400, w14_count, "w14");
  float *b53 = read_floats_at(wf, 1112832, b53_count, "b53");
  float *b54 = read_floats_at(wf, 1114880, b54_count, "b54");
  float *b55 = read_floats_at(wf, 1116928, b55_count, "b55");
  float *b56 = read_floats_at(wf, 1118976, b56_count, "b56");
  float *w15 = read_floats_at(wf, 1121024, w15_count, "w15");
  float *b57 = read_floats_at(wf, 2169600, b57_count, "b57");
  float *b58 = read_floats_at(wf, 2171648, b58_count, "b58");
  float *b59 = read_floats_at(wf, 2173696, b59_count, "b59");
  float *b60 = read_floats_at(wf, 2175744, b60_count, "b60");
  float *w16 = read_floats_at(wf, 2177792, w16_count, "w16");
  float *b61 = read_floats_at(wf, 2196224, b61_count, "b61");
  float *b62 = read_floats_at(wf, 2198272, b62_count, "b62");
  float *b63 = read_floats_at(wf, 2200320, b63_count, "b63");
  float *b64 = read_floats_at(wf, 2202368, b64_count, "b64");
  float *w17 = read_floats_at(wf, 2204416, w17_count, "w17");
  float *b65 = read_floats_at(wf, 3252992, b65_count, "b65");
  float *b66 = read_floats_at(wf, 3255040, b66_count, "b66");
  float *b67 = read_floats_at(wf, 3257088, b67_count, "b67");
  float *b68 = read_floats_at(wf, 3259136, b68_count, "b68");
  float *w18 = read_floats_at(wf, 3261184, w18_count, "w18");
  float *b69 = read_floats_at(wf, 3279616, b69_count, "b69");
  float *b70 = read_floats_at(wf, 3281664, b70_count, "b70");
  float *b71 = read_floats_at(wf, 3283712, b71_count, "b71");
  float *b72 = read_floats_at(wf, 3285760, b72_count, "b72");
  float *w19 = read_floats_at(wf, 3287808, w19_count, "w19");
  float *b73 = read_floats_at(wf, 4336384, b73_count, "b73");
  float *b74 = read_floats_at(wf, 4338432, b74_count, "b74");
  float *b75 = read_floats_at(wf, 4340480, b75_count, "b75");
  float *b76 = read_floats_at(wf, 4342528, b76_count, "b76");
  float *w20 = read_floats_at(wf, 4344576, w20_count, "w20");
  float *b77 = read_floats_at(wf, 4363008, b77_count, "b77");
  float *b78 = read_floats_at(wf, 4365056, b78_count, "b78");
  float *b79 = read_floats_at(wf, 4367104, b79_count, "b79");
  float *b80 = read_floats_at(wf, 4369152, b80_count, "b80");
  float *w21 = read_floats_at(wf, 4371200, w21_count, "w21");
  float *b81 = read_floats_at(wf, 5419776, b81_count, "b81");
  float *b82 = read_floats_at(wf, 5421824, b82_count, "b82");
  float *b83 = read_floats_at(wf, 5423872, b83_count, "b83");
  float *b84 = read_floats_at(wf, 5425920, b84_count, "b84");
  float *w22 = read_floats_at(wf, 5427968, w22_count, "w22");
  float *b85 = read_floats_at(wf, 5446400, b85_count, "b85");
  float *b86 = read_floats_at(wf, 5448448, b86_count, "b86");
  float *b87 = read_floats_at(wf, 5450496, b87_count, "b87");
  float *b88 = read_floats_at(wf, 5452544, b88_count, "b88");
  float *w23 = read_floats_at(wf, 5454592, w23_count, "w23");
  float *b89 = read_floats_at(wf, 6503168, b89_count, "b89");
  float *b90 = read_floats_at(wf, 6505216, b90_count, "b90");
  float *b91 = read_floats_at(wf, 6507264, b91_count, "b91");
  float *b92 = read_floats_at(wf, 6509312, b92_count, "b92");
  float *w24 = read_floats_at(wf, 6511360, w24_count, "w24");
  float *b93 = read_floats_at(wf, 6529792, b93_count, "b93");
  float *b94 = read_floats_at(wf, 6531840, b94_count, "b94");
  float *b95 = read_floats_at(wf, 6533888, b95_count, "b95");
  float *b96 = read_floats_at(wf, 6535936, b96_count, "b96");
  float *w25 = read_floats_at(wf, 6537984, w25_count, "w25");
  float *b97 = read_floats_at(wf, 8635136, b97_count, "b97");
  float *b98 = read_floats_at(wf, 8639232, b98_count, "b98");
  float *b99 = read_floats_at(wf, 8643328, b99_count, "b99");
  float *b100 = read_floats_at(wf, 8647424, b100_count, "b100");
  float *w26 = read_floats_at(wf, 8651520, w26_count, "w26");
  float *b101 = read_floats_at(wf, 8688384, b101_count, "b101");
  float *b102 = read_floats_at(wf, 8692480, b102_count, "b102");
  float *b103 = read_floats_at(wf, 8696576, b103_count, "b103");
  float *b104 = read_floats_at(wf, 8700672, b104_count, "b104");
  float *w27 = read_floats_at(wf, 8704768, w27_count, "w27");
  float *b105 = read_floats_at(wf, 12899072, b105_count, "b105");
  float *b106 = read_floats_at(wf, 12903168, b106_count, "b106");
  float *b107 = read_floats_at(wf, 12907264, b107_count, "b107");
  float *b108 = read_floats_at(wf, 12911360, b108_count, "b108");
  float *w28 = read_floats_at(wf, 12915456, w28_count, "w28");
  float *b109 = read_floats_at(wf, 17011456, b109_count, "b109");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  const int use_fork = driver_fork_enabled();
  double *times = use_fork ? alloc_shared_times(reps)
                           : (double *)malloc(reps * sizeof(double));
  printf("call isolation: %s\n", use_fork ? "fork per call" : "in-process (DRIVER_NO_FORK)");

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  if (use_fork) {
    fflush(NULL);
    pid_t p = fork();
    if (p < 0) { perror("fork"); return 1; }
    if (p == 0) {
      float *out = MobileNetV1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93, b94, b95, b96, w25, b97, b98, b99, b100, w26, b101, b102, b103, b104, w27, b105, b106, b107, b108, w28, b109);
      free(out);
      _exit(0);
    }
    await_child(p, "warm-up");
  } else {
    float *out = MobileNetV1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93, b94, b95, b96, w25, b97, b98, b99, b100, w26, b101, b102, b103, b104, w27, b105, b106, b107, b108, w28, b109);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    const int is_last = (i == reps - 1);
    if (use_fork) {
      fflush(NULL);
      pid_t p = fork();
      if (p < 0) { perror("fork"); return 1; }
      if (p == 0) {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        float *cur = MobileNetV1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93, b94, b95, b96, w25, b97, b98, b99, b100, w26, b101, b102, b103, b104, w27, b105, b106, b107, b108, w28, b109);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                   (double)(t1.tv_nsec - t0.tv_nsec);
        /* The last rep's child owns writing the result -- that keeps the
           output buffer from having to cross the process boundary.
           write_result() frees `cur`. */
        if (is_last)
          write_result(cur, output_path);
        _exit(0);
      }
      await_child(p, "timed rep");
    } else {
      struct timespec t0, t1;
      clock_gettime(CLOCK_MONOTONIC, &t0);
      float *cur = MobileNetV1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93, b94, b95, b96, w25, b97, b98, b99, b100, w26, b101, b102, b103, b104, w27, b105, b106, b107, b108, w28, b109);
      clock_gettime(CLOCK_MONOTONIC, &t1);
      times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                 (double)(t1.tv_nsec - t0.tv_nsec);
      if (out)
        free(out);
      out = cur;
    }
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  if (!use_fork)
    write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  write_timing_report(json_report_path, "MobileNetV1", "mim_llvm", run_id,
                       weights_path, input_path, output_path, reps,
                       times[reps / 2], sum / reps, times[0], times[reps - 1]);

  free(x);
  release_times(times, reps, use_fork);
  return 0;
}
