#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

/* Auto-generated driver for `RegNet` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * w1: shape [64, 3, 3, 3] (weight) <- feature_extractor.0.0.weight @ byte 0
 * b1: shape [64] (bias) <- feature_extractor.0.0.bias @ byte 6912
 * x: shape [8, 3, 224, 224] (input)
 * b2: shape [64] (bias) <- feature_extractor.0.1.running_mean @ byte 7168
 * b3: shape [64] (bias) <- feature_extractor.0.1.running_var @ byte 7424
 * b4: shape [64] (bias) <- feature_extractor.0.1.weight @ byte 7680
 * b5: shape [64] (bias) <- feature_extractor.0.1.bias @ byte 7936
 * w2: shape [64, 64, 3, 3] (weight) <- feature_extractor.0.3.weight @ byte 8192
 * b6: shape [64] (bias) <- feature_extractor.0.3.bias @ byte 155648
 * b7: shape [64] (bias) <- feature_extractor.0.4.running_mean @ byte 155904
 * b8: shape [64] (bias) <- feature_extractor.0.4.running_var @ byte 156160
 * b9: shape [64] (bias) <- feature_extractor.0.4.weight @ byte 156416
 * b10: shape [64] (bias) <- feature_extractor.0.4.bias @ byte 156672
 * w3: shape [128, 64, 3, 3] (weight) <- feature_extractor.1.0.weight @ byte 156928
 * b11: shape [128] (bias) <- feature_extractor.1.0.bias @ byte 451840
 * b12: shape [128] (bias) <- feature_extractor.1.1.running_mean @ byte 452352
 * b13: shape [128] (bias) <- feature_extractor.1.1.running_var @ byte 452864
 * b14: shape [128] (bias) <- feature_extractor.1.1.weight @ byte 453376
 * b15: shape [128] (bias) <- feature_extractor.1.1.bias @ byte 453888
 * w4: shape [128, 128, 3, 3] (weight) <- feature_extractor.1.3.weight @ byte 454400
 * b16: shape [128] (bias) <- feature_extractor.1.3.bias @ byte 1044224
 * b17: shape [128] (bias) <- feature_extractor.1.4.running_mean @ byte 1044736
 * b18: shape [128] (bias) <- feature_extractor.1.4.running_var @ byte 1045248
 * b19: shape [128] (bias) <- feature_extractor.1.4.weight @ byte 1045760
 * b20: shape [128] (bias) <- feature_extractor.1.4.bias @ byte 1046272
 * w5: shape [256, 128, 3, 3] (weight) <- feature_extractor.2.0.weight @ byte 1046784
 * b21: shape [256] (bias) <- feature_extractor.2.0.bias @ byte 2226432
 * b22: shape [256] (bias) <- feature_extractor.2.1.running_mean @ byte 2227456
 * b23: shape [256] (bias) <- feature_extractor.2.1.running_var @ byte 2228480
 * b24: shape [256] (bias) <- feature_extractor.2.1.weight @ byte 2229504
 * b25: shape [256] (bias) <- feature_extractor.2.1.bias @ byte 2230528
 * w6: shape [256, 256, 3, 3] (weight) <- feature_extractor.2.3.weight @ byte 2231552
 * b26: shape [256] (bias) <- feature_extractor.2.3.bias @ byte 4590848
 * b27: shape [256] (bias) <- feature_extractor.2.4.running_mean @ byte 4591872
 * b28: shape [256] (bias) <- feature_extractor.2.4.running_var @ byte 4592896
 * b29: shape [256] (bias) <- feature_extractor.2.4.weight @ byte 4593920
 * b30: shape [256] (bias) <- feature_extractor.2.4.bias @ byte 4594944
 * w7: shape [10, 256] (weight) <- fc.weight @ byte 4595968
 * b31: shape [10] (bias) <- fc.bias @ byte 4606208
 * output: shape [8, 10]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 *
 * Usage: RegNet_driver_mim <weights> <input> <reps> <output> [run_id] [json_report]
 * run_id/json_report default to a generated UTC timestamp / a filename
 * derived from it if omitted -- pass the same run_id across every model
 * and pipeline in one batch (e.g. from reporter.py) to correlate their
 * timing reports.
 */
extern float *RegNet(float *w1, float *b1, float *x, float *b2, float *b3, float *b4, float *b5, float *w2, float *b6, float *b7, float *b8, float *b9, float *b10, float *w3, float *b11, float *b12, float *b13, float *b14, float *b15, float *w4, float *b16, float *b17, float *b18, float *b19, float *b20, float *w5, float *b21, float *b22, float *b23, float *b24, float *b25, float *w6, float *b26, float *b27, float *b28, float *b29, float *b30, float *w7, float *b31);

static const size_t w1_count = 1728;
static const size_t b1_count = 64;
static const size_t x_count = 1204224;
static const size_t b2_count = 64;
static const size_t b3_count = 64;
static const size_t b4_count = 64;
static const size_t b5_count = 64;
static const size_t w2_count = 36864;
static const size_t b6_count = 64;
static const size_t b7_count = 64;
static const size_t b8_count = 64;
static const size_t b9_count = 64;
static const size_t b10_count = 64;
static const size_t w3_count = 73728;
static const size_t b11_count = 128;
static const size_t b12_count = 128;
static const size_t b13_count = 128;
static const size_t b14_count = 128;
static const size_t b15_count = 128;
static const size_t w4_count = 147456;
static const size_t b16_count = 128;
static const size_t b17_count = 128;
static const size_t b18_count = 128;
static const size_t b19_count = 128;
static const size_t b20_count = 128;
static const size_t w5_count = 294912;
static const size_t b21_count = 256;
static const size_t b22_count = 256;
static const size_t b23_count = 256;
static const size_t b24_count = 256;
static const size_t b25_count = 256;
static const size_t w6_count = 589824;
static const size_t b26_count = 256;
static const size_t b27_count = 256;
static const size_t b28_count = 256;
static const size_t b29_count = 256;
static const size_t b30_count = 256;
static const size_t w7_count = 2560;
static const size_t b31_count = 10;
static const size_t OUT_COUNT = 80;

static float *read_floats_at(FILE *f, long byte_offset, size_t n,
                             const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  if (fseek(f, byte_offset, SEEK_SET) != 0) {
    fprintf(stderr, "seek to offset %ld for %s failed\n", byte_offset, what);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s at offset %ld: wanted %zu floats, got "
                    "%zu\n", what, byte_offset, n, got);
    exit(1);
  }
  return p;
}

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void resolve_run_id(int argc, char **argv, char *buf, size_t buflen) {
  if (argc > 5) {
    snprintf(buf, buflen, "%s", argv[5]);
    return;
  }
  time_t now = time(NULL);
  struct tm tm_utc;
  gmtime_r(&now, &tm_utc);
  strftime(buf, buflen, "%Y%m%d_%H%M%S", &tm_utc);
}

static void print_json_string(FILE *f, const char *s) {
  fputc('"', f);
  for (const char *p = s; *p; p++) {
    if (*p == '"' || *p == '\\')
      fputc('\\', f);
    fputc(*p, f);
  }
  fputc('"', f);
}

static void write_timing_report(const char *json_path, const char *model,
                                 const char *pipeline, const char *run_id,
                                 const char *weights_path, const char *input_path,
                                 const char *output_path, int reps,
                                 double median_ns, double mean_ns, double min_ns,
                                 double max_ns) {
  FILE *jf = fopen(json_path, "w");
  if (!jf) {
    fprintf(stderr, "warning: failed to write timing report '%s': ", json_path);
    perror(NULL);
    return;
  }
  fprintf(jf, "{\n  \"model\": ");
  print_json_string(jf, model);
  fprintf(jf, ",\n  \"pipeline\": ");
  print_json_string(jf, pipeline);
  fprintf(jf, ",\n  \"run_id\": ");
  print_json_string(jf, run_id);
  fprintf(jf, ",\n  \"weights_path\": ");
  print_json_string(jf, weights_path);
  fprintf(jf, ",\n  \"input_path\": ");
  print_json_string(jf, input_path);
  fprintf(jf, ",\n  \"output_path\": ");
  print_json_string(jf, output_path);
  fprintf(jf, ",\n  \"reps\": %d", reps);
  fprintf(jf, ",\n  \"median_ns\": %.1f", median_ns);
  fprintf(jf, ",\n  \"mean_ns\": %.1f", mean_ns);
  fprintf(jf, ",\n  \"min_ns\": %.1f", min_ns);
  fprintf(jf, ",\n  \"max_ns\": %.1f", max_ns);
  fprintf(jf, "\n}\n");
  fclose(jf);
  printf("wrote timing report to %s\n", json_path);
  fflush(stdout);
}

/* --- per-call process isolation; see c_fork_helpers() in gen_drivers.py ---
 * Each call to the model runs in a forked child, so the leak of its
 * internal intermediates cannot accumulate across reps. Weights and input
 * are inherited copy-on-write and are NOT duplicated. Elapsed times come
 * back through a shared anonymous mapping, and the final rep's child writes
 * the output file itself so the result never has to cross the process
 * boundary.
 *
 * Set DRIVER_NO_FORK=1 to run every call in-process instead -- the previous
 * behaviour, for A/B or for profilers that dislike fork.
 */
static int driver_fork_enabled(void) {
  const char *e = getenv("DRIVER_NO_FORK");
  return !(e && e[0] && e[0] != '0');
}

static double *alloc_shared_times(int reps) {
  size_t n = (size_t)reps * sizeof(double);
  void *p = mmap(NULL, n, PROT_READ | PROT_WRITE,
                 MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  if (p == MAP_FAILED) {
    perror("mmap for shared timing buffer");
    exit(1);
  }
  return (double *)p;
}

static void await_child(pid_t pid, const char *what) {
  int st = 0;
  if (waitpid(pid, &st, 0) < 0) {
    perror("waitpid");
    exit(1);
  }
  if (WIFSIGNALED(st)) {
    int s = WTERMSIG(st);
    fprintf(stderr, "%s: child killed by signal %d\n", what, s);
    if (s == SIGKILL)
      fprintf(stderr,
              "  SIGKILL almost always means the OOM killer. This model "
              "leaks several GiB\n  per call inside the generated code; a "
              "single call already exceeds free RAM.\n  Forking bounds the "
              "leak to one call, so it cannot help beyond that.\n");
    exit(1);
  }
  if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
    fprintf(stderr, "%s: child exited with status %d\n", what,
            WIFEXITED(st) ? WEXITSTATUS(st) : -1);
    exit(1);
  }
}

static void release_times(double *times, int reps, int forked) {
  if (forked)
    munmap(times, (size_t)reps * sizeof(double));
  else
    free(times);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  char run_id_buf[64];
  resolve_run_id(argc, argv, run_id_buf, sizeof(run_id_buf));
  const char *run_id = run_id_buf;

  char json_path_buf[512];
  const char *json_report_path;
  if (argc > 6) {
    json_report_path = argv[6];
  } else {
    snprintf(json_path_buf, sizeof(json_path_buf), "RegNet_mim_llvm_%s_timing.json", run_id);
    json_report_path = json_path_buf;
  }

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *w1 = read_floats_at(wf, 0, w1_count, "w1");
  float *b1 = read_floats_at(wf, 6912, b1_count, "b1");
  float *b2 = read_floats_at(wf, 7168, b2_count, "b2");
  float *b3 = read_floats_at(wf, 7424, b3_count, "b3");
  float *b4 = read_floats_at(wf, 7680, b4_count, "b4");
  float *b5 = read_floats_at(wf, 7936, b5_count, "b5");
  float *w2 = read_floats_at(wf, 8192, w2_count, "w2");
  float *b6 = read_floats_at(wf, 155648, b6_count, "b6");
  float *b7 = read_floats_at(wf, 155904, b7_count, "b7");
  float *b8 = read_floats_at(wf, 156160, b8_count, "b8");
  float *b9 = read_floats_at(wf, 156416, b9_count, "b9");
  float *b10 = read_floats_at(wf, 156672, b10_count, "b10");
  float *w3 = read_floats_at(wf, 156928, w3_count, "w3");
  float *b11 = read_floats_at(wf, 451840, b11_count, "b11");
  float *b12 = read_floats_at(wf, 452352, b12_count, "b12");
  float *b13 = read_floats_at(wf, 452864, b13_count, "b13");
  float *b14 = read_floats_at(wf, 453376, b14_count, "b14");
  float *b15 = read_floats_at(wf, 453888, b15_count, "b15");
  float *w4 = read_floats_at(wf, 454400, w4_count, "w4");
  float *b16 = read_floats_at(wf, 1044224, b16_count, "b16");
  float *b17 = read_floats_at(wf, 1044736, b17_count, "b17");
  float *b18 = read_floats_at(wf, 1045248, b18_count, "b18");
  float *b19 = read_floats_at(wf, 1045760, b19_count, "b19");
  float *b20 = read_floats_at(wf, 1046272, b20_count, "b20");
  float *w5 = read_floats_at(wf, 1046784, w5_count, "w5");
  float *b21 = read_floats_at(wf, 2226432, b21_count, "b21");
  float *b22 = read_floats_at(wf, 2227456, b22_count, "b22");
  float *b23 = read_floats_at(wf, 2228480, b23_count, "b23");
  float *b24 = read_floats_at(wf, 2229504, b24_count, "b24");
  float *b25 = read_floats_at(wf, 2230528, b25_count, "b25");
  float *w6 = read_floats_at(wf, 2231552, w6_count, "w6");
  float *b26 = read_floats_at(wf, 4590848, b26_count, "b26");
  float *b27 = read_floats_at(wf, 4591872, b27_count, "b27");
  float *b28 = read_floats_at(wf, 4592896, b28_count, "b28");
  float *b29 = read_floats_at(wf, 4593920, b29_count, "b29");
  float *b30 = read_floats_at(wf, 4594944, b30_count, "b30");
  float *w7 = read_floats_at(wf, 4595968, w7_count, "w7");
  float *b31 = read_floats_at(wf, 4606208, b31_count, "b31");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  const int use_fork = driver_fork_enabled();
  double *times = use_fork ? alloc_shared_times(reps)
                           : (double *)malloc(reps * sizeof(double));
  printf("call isolation: %s\n", use_fork ? "fork per call" : "in-process (DRIVER_NO_FORK)");

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  if (use_fork) {
    fflush(NULL);
    pid_t p = fork();
    if (p < 0) { perror("fork"); return 1; }
    if (p == 0) {
      float *out = RegNet(w1, b1, x, b2, b3, b4, b5, w2, b6, b7, b8, b9, b10, w3, b11, b12, b13, b14, b15, w4, b16, b17, b18, b19, b20, w5, b21, b22, b23, b24, b25, w6, b26, b27, b28, b29, b30, w7, b31);
      free(out);
      _exit(0);
    }
    await_child(p, "warm-up");
  } else {
    float *out = RegNet(w1, b1, x, b2, b3, b4, b5, w2, b6, b7, b8, b9, b10, w3, b11, b12, b13, b14, b15, w4, b16, b17, b18, b19, b20, w5, b21, b22, b23, b24, b25, w6, b26, b27, b28, b29, b30, w7, b31);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    const int is_last = (i == reps - 1);
    if (use_fork) {
      fflush(NULL);
      pid_t p = fork();
      if (p < 0) { perror("fork"); return 1; }
      if (p == 0) {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        float *cur = RegNet(w1, b1, x, b2, b3, b4, b5, w2, b6, b7, b8, b9, b10, w3, b11, b12, b13, b14, b15, w4, b16, b17, b18, b19, b20, w5, b21, b22, b23, b24, b25, w6, b26, b27, b28, b29, b30, w7, b31);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                   (double)(t1.tv_nsec - t0.tv_nsec);
        /* The last rep's child owns writing the result -- that keeps the
           output buffer from having to cross the process boundary.
           write_result() frees `cur`. */
        if (is_last)
          write_result(cur, output_path);
        _exit(0);
      }
      await_child(p, "timed rep");
    } else {
      struct timespec t0, t1;
      clock_gettime(CLOCK_MONOTONIC, &t0);
      float *cur = RegNet(w1, b1, x, b2, b3, b4, b5, w2, b6, b7, b8, b9, b10, w3, b11, b12, b13, b14, b15, w4, b16, b17, b18, b19, b20, w5, b21, b22, b23, b24, b25, w6, b26, b27, b28, b29, b30, w7, b31);
      clock_gettime(CLOCK_MONOTONIC, &t1);
      times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                 (double)(t1.tv_nsec - t0.tv_nsec);
      if (out)
        free(out);
      out = cur;
    }
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  if (!use_fork)
    write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  write_timing_report(json_report_path, "RegNet", "mim_llvm", run_id,
                       weights_path, input_path, output_path, reps,
                       times[reps / 2], sum / reps, times[0], times[reps - 1]);

  free(x);
  release_times(times, reps, use_fork);
  return 0;
}
