#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

/* Auto-generated driver for `EfficientNetB1` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * w1: shape [32, 3, 3, 3] (weight) <- conv1.weight @ byte 0
 * x: shape [10, 3, 240, 240] (input)
 * b1: shape [32] (bias) <- bn1.running_mean @ byte 3456
 * b2: shape [32] (bias) <- bn1.running_var @ byte 3584
 * b3: shape [32] (bias) <- bn1.weight @ byte 3712
 * b4: shape [32] (bias) <- bn1.bias @ byte 3840
 * w2: shape [32, 32] (weight) <- mbconv1.0.weight @ byte 3968
 * b5: shape [32] (bias) <- mbconv1.1.running_mean @ byte 8064
 * b6: shape [32] (bias) <- mbconv1.1.running_var @ byte 8192
 * b7: shape [32] (bias) <- mbconv1.1.weight @ byte 8320
 * b8: shape [32] (bias) <- mbconv1.1.bias @ byte 8448
 * w3: shape [32, 3, 3] (weight) <- mbconv1.3.weight @ byte 8576
 * b9: shape [32] (bias) <- mbconv1.4.running_mean @ byte 9728
 * b10: shape [32] (bias) <- mbconv1.4.running_var @ byte 9856
 * b11: shape [32] (bias) <- mbconv1.4.weight @ byte 9984
 * b12: shape [32] (bias) <- mbconv1.4.bias @ byte 10112
 * w4: shape [16, 32] (weight) <- mbconv1.6.weight @ byte 10240
 * b13: shape [16] (bias) <- mbconv1.7.running_mean @ byte 12288
 * b14: shape [16] (bias) <- mbconv1.7.running_var @ byte 12352
 * b15: shape [16] (bias) <- mbconv1.7.weight @ byte 12416
 * b16: shape [16] (bias) <- mbconv1.7.bias @ byte 12480
 * w5: shape [96, 16] (weight) <- mbconv2.0.weight @ byte 12544
 * b17: shape [96] (bias) <- mbconv2.1.running_mean @ byte 18688
 * b18: shape [96] (bias) <- mbconv2.1.running_var @ byte 19072
 * b19: shape [96] (bias) <- mbconv2.1.weight @ byte 19456
 * b20: shape [96] (bias) <- mbconv2.1.bias @ byte 19840
 * w6: shape [96, 3, 3] (weight) <- mbconv2.3.weight @ byte 20224
 * b21: shape [96] (bias) <- mbconv2.4.running_mean @ byte 23680
 * b22: shape [96] (bias) <- mbconv2.4.running_var @ byte 24064
 * b23: shape [96] (bias) <- mbconv2.4.weight @ byte 24448
 * b24: shape [96] (bias) <- mbconv2.4.bias @ byte 24832
 * w7: shape [24, 96] (weight) <- mbconv2.6.weight @ byte 25216
 * b25: shape [24] (bias) <- mbconv2.7.running_mean @ byte 34432
 * b26: shape [24] (bias) <- mbconv2.7.running_var @ byte 34528
 * b27: shape [24] (bias) <- mbconv2.7.weight @ byte 34624
 * b28: shape [24] (bias) <- mbconv2.7.bias @ byte 34720
 * w8: shape [144, 24] (weight) <- mbconv3.0.weight @ byte 34816
 * b29: shape [144] (bias) <- mbconv3.1.running_mean @ byte 48640
 * b30: shape [144] (bias) <- mbconv3.1.running_var @ byte 49216
 * b31: shape [144] (bias) <- mbconv3.1.weight @ byte 49792
 * b32: shape [144] (bias) <- mbconv3.1.bias @ byte 50368
 * w9: shape [144, 3, 3] (weight) <- mbconv3.3.weight @ byte 50944
 * b33: shape [144] (bias) <- mbconv3.4.running_mean @ byte 56128
 * b34: shape [144] (bias) <- mbconv3.4.running_var @ byte 56704
 * b35: shape [144] (bias) <- mbconv3.4.weight @ byte 57280
 * b36: shape [144] (bias) <- mbconv3.4.bias @ byte 57856
 * w10: shape [40, 144] (weight) <- mbconv3.6.weight @ byte 58432
 * b37: shape [40] (bias) <- mbconv3.7.running_mean @ byte 81472
 * b38: shape [40] (bias) <- mbconv3.7.running_var @ byte 81632
 * b39: shape [40] (bias) <- mbconv3.7.weight @ byte 81792
 * b40: shape [40] (bias) <- mbconv3.7.bias @ byte 81952
 * w11: shape [240, 40] (weight) <- mbconv4.0.weight @ byte 82112
 * b41: shape [240] (bias) <- mbconv4.1.running_mean @ byte 120512
 * b42: shape [240] (bias) <- mbconv4.1.running_var @ byte 121472
 * b43: shape [240] (bias) <- mbconv4.1.weight @ byte 122432
 * b44: shape [240] (bias) <- mbconv4.1.bias @ byte 123392
 * w12: shape [240, 3, 3] (weight) <- mbconv4.3.weight @ byte 124352
 * b45: shape [240] (bias) <- mbconv4.4.running_mean @ byte 132992
 * b46: shape [240] (bias) <- mbconv4.4.running_var @ byte 133952
 * b47: shape [240] (bias) <- mbconv4.4.weight @ byte 134912
 * b48: shape [240] (bias) <- mbconv4.4.bias @ byte 135872
 * w13: shape [80, 240] (weight) <- mbconv4.6.weight @ byte 136832
 * b49: shape [80] (bias) <- mbconv4.7.running_mean @ byte 213632
 * b50: shape [80] (bias) <- mbconv4.7.running_var @ byte 213952
 * b51: shape [80] (bias) <- mbconv4.7.weight @ byte 214272
 * b52: shape [80] (bias) <- mbconv4.7.bias @ byte 214592
 * w14: shape [480, 80] (weight) <- mbconv5.0.weight @ byte 214912
 * b53: shape [480] (bias) <- mbconv5.1.running_mean @ byte 368512
 * b54: shape [480] (bias) <- mbconv5.1.running_var @ byte 370432
 * b55: shape [480] (bias) <- mbconv5.1.weight @ byte 372352
 * b56: shape [480] (bias) <- mbconv5.1.bias @ byte 374272
 * w15: shape [480, 3, 3] (weight) <- mbconv5.3.weight @ byte 376192
 * b57: shape [480] (bias) <- mbconv5.4.running_mean @ byte 393472
 * b58: shape [480] (bias) <- mbconv5.4.running_var @ byte 395392
 * b59: shape [480] (bias) <- mbconv5.4.weight @ byte 397312
 * b60: shape [480] (bias) <- mbconv5.4.bias @ byte 399232
 * w16: shape [112, 480] (weight) <- mbconv5.6.weight @ byte 401152
 * b61: shape [112] (bias) <- mbconv5.7.running_mean @ byte 616192
 * b62: shape [112] (bias) <- mbconv5.7.running_var @ byte 616640
 * b63: shape [112] (bias) <- mbconv5.7.weight @ byte 617088
 * b64: shape [112] (bias) <- mbconv5.7.bias @ byte 617536
 * w17: shape [672, 112] (weight) <- mbconv6.0.weight @ byte 617984
 * b65: shape [672] (bias) <- mbconv6.1.running_mean @ byte 919040
 * b66: shape [672] (bias) <- mbconv6.1.running_var @ byte 921728
 * b67: shape [672] (bias) <- mbconv6.1.weight @ byte 924416
 * b68: shape [672] (bias) <- mbconv6.1.bias @ byte 927104
 * w18: shape [672, 3, 3] (weight) <- mbconv6.3.weight @ byte 929792
 * b69: shape [672] (bias) <- mbconv6.4.running_mean @ byte 953984
 * b70: shape [672] (bias) <- mbconv6.4.running_var @ byte 956672
 * b71: shape [672] (bias) <- mbconv6.4.weight @ byte 959360
 * b72: shape [672] (bias) <- mbconv6.4.bias @ byte 962048
 * w19: shape [192, 672] (weight) <- mbconv6.6.weight @ byte 964736
 * b73: shape [192] (bias) <- mbconv6.7.running_mean @ byte 1480832
 * b74: shape [192] (bias) <- mbconv6.7.running_var @ byte 1481600
 * b75: shape [192] (bias) <- mbconv6.7.weight @ byte 1482368
 * b76: shape [192] (bias) <- mbconv6.7.bias @ byte 1483136
 * w20: shape [1152, 192] (weight) <- mbconv7.0.weight @ byte 1483904
 * b77: shape [1152] (bias) <- mbconv7.1.running_mean @ byte 2368640
 * b78: shape [1152] (bias) <- mbconv7.1.running_var @ byte 2373248
 * b79: shape [1152] (bias) <- mbconv7.1.weight @ byte 2377856
 * b80: shape [1152] (bias) <- mbconv7.1.bias @ byte 2382464
 * w21: shape [1152, 3, 3] (weight) <- mbconv7.3.weight @ byte 2387072
 * b81: shape [1152] (bias) <- mbconv7.4.running_mean @ byte 2428544
 * b82: shape [1152] (bias) <- mbconv7.4.running_var @ byte 2433152
 * b83: shape [1152] (bias) <- mbconv7.4.weight @ byte 2437760
 * b84: shape [1152] (bias) <- mbconv7.4.bias @ byte 2442368
 * w22: shape [320, 1152] (weight) <- mbconv7.6.weight @ byte 2446976
 * b85: shape [320] (bias) <- mbconv7.7.running_mean @ byte 3921536
 * b86: shape [320] (bias) <- mbconv7.7.running_var @ byte 3922816
 * b87: shape [320] (bias) <- mbconv7.7.weight @ byte 3924096
 * b88: shape [320] (bias) <- mbconv7.7.bias @ byte 3925376
 * w23: shape [1280, 320] (weight) <- conv2.weight @ byte 3926656
 * b89: shape [1280] (bias) <- bn2.running_mean @ byte 5565056
 * b90: shape [1280] (bias) <- bn2.running_var @ byte 5570176
 * b91: shape [1280] (bias) <- bn2.weight @ byte 5575296
 * b92: shape [1280] (bias) <- bn2.bias @ byte 5580416
 * w24: shape [1000, 1280] (weight) <- fc.weight @ byte 5585536
 * b93: shape [1000] (bias) <- fc.bias @ byte 10705536
 * output: shape [10, 1000]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 *
 * Usage: EfficientNetB1_driver_mim <weights> <input> <reps> <output> [run_id] [json_report]
 * run_id/json_report default to a generated UTC timestamp / a filename
 * derived from it if omitted -- pass the same run_id across every model
 * and pipeline in one batch (e.g. from reporter.py) to correlate their
 * timing reports.
 */
extern float *EfficientNetB1(float *w1, float *x, float *b1, float *b2, float *b3, float *b4, float *w2, float *b5, float *b6, float *b7, float *b8, float *w3, float *b9, float *b10, float *b11, float *b12, float *w4, float *b13, float *b14, float *b15, float *b16, float *w5, float *b17, float *b18, float *b19, float *b20, float *w6, float *b21, float *b22, float *b23, float *b24, float *w7, float *b25, float *b26, float *b27, float *b28, float *w8, float *b29, float *b30, float *b31, float *b32, float *w9, float *b33, float *b34, float *b35, float *b36, float *w10, float *b37, float *b38, float *b39, float *b40, float *w11, float *b41, float *b42, float *b43, float *b44, float *w12, float *b45, float *b46, float *b47, float *b48, float *w13, float *b49, float *b50, float *b51, float *b52, float *w14, float *b53, float *b54, float *b55, float *b56, float *w15, float *b57, float *b58, float *b59, float *b60, float *w16, float *b61, float *b62, float *b63, float *b64, float *w17, float *b65, float *b66, float *b67, float *b68, float *w18, float *b69, float *b70, float *b71, float *b72, float *w19, float *b73, float *b74, float *b75, float *b76, float *w20, float *b77, float *b78, float *b79, float *b80, float *w21, float *b81, float *b82, float *b83, float *b84, float *w22, float *b85, float *b86, float *b87, float *b88, float *w23, float *b89, float *b90, float *b91, float *b92, float *w24, float *b93);

static const size_t w1_count = 864;
static const size_t x_count = 1728000;
static const size_t b1_count = 32;
static const size_t b2_count = 32;
static const size_t b3_count = 32;
static const size_t b4_count = 32;
static const size_t w2_count = 1024;
static const size_t b5_count = 32;
static const size_t b6_count = 32;
static const size_t b7_count = 32;
static const size_t b8_count = 32;
static const size_t w3_count = 288;
static const size_t b9_count = 32;
static const size_t b10_count = 32;
static const size_t b11_count = 32;
static const size_t b12_count = 32;
static const size_t w4_count = 512;
static const size_t b13_count = 16;
static const size_t b14_count = 16;
static const size_t b15_count = 16;
static const size_t b16_count = 16;
static const size_t w5_count = 1536;
static const size_t b17_count = 96;
static const size_t b18_count = 96;
static const size_t b19_count = 96;
static const size_t b20_count = 96;
static const size_t w6_count = 864;
static const size_t b21_count = 96;
static const size_t b22_count = 96;
static const size_t b23_count = 96;
static const size_t b24_count = 96;
static const size_t w7_count = 2304;
static const size_t b25_count = 24;
static const size_t b26_count = 24;
static const size_t b27_count = 24;
static const size_t b28_count = 24;
static const size_t w8_count = 3456;
static const size_t b29_count = 144;
static const size_t b30_count = 144;
static const size_t b31_count = 144;
static const size_t b32_count = 144;
static const size_t w9_count = 1296;
static const size_t b33_count = 144;
static const size_t b34_count = 144;
static const size_t b35_count = 144;
static const size_t b36_count = 144;
static const size_t w10_count = 5760;
static const size_t b37_count = 40;
static const size_t b38_count = 40;
static const size_t b39_count = 40;
static const size_t b40_count = 40;
static const size_t w11_count = 9600;
static const size_t b41_count = 240;
static const size_t b42_count = 240;
static const size_t b43_count = 240;
static const size_t b44_count = 240;
static const size_t w12_count = 2160;
static const size_t b45_count = 240;
static const size_t b46_count = 240;
static const size_t b47_count = 240;
static const size_t b48_count = 240;
static const size_t w13_count = 19200;
static const size_t b49_count = 80;
static const size_t b50_count = 80;
static const size_t b51_count = 80;
static const size_t b52_count = 80;
static const size_t w14_count = 38400;
static const size_t b53_count = 480;
static const size_t b54_count = 480;
static const size_t b55_count = 480;
static const size_t b56_count = 480;
static const size_t w15_count = 4320;
static const size_t b57_count = 480;
static const size_t b58_count = 480;
static const size_t b59_count = 480;
static const size_t b60_count = 480;
static const size_t w16_count = 53760;
static const size_t b61_count = 112;
static const size_t b62_count = 112;
static const size_t b63_count = 112;
static const size_t b64_count = 112;
static const size_t w17_count = 75264;
static const size_t b65_count = 672;
static const size_t b66_count = 672;
static const size_t b67_count = 672;
static const size_t b68_count = 672;
static const size_t w18_count = 6048;
static const size_t b69_count = 672;
static const size_t b70_count = 672;
static const size_t b71_count = 672;
static const size_t b72_count = 672;
static const size_t w19_count = 129024;
static const size_t b73_count = 192;
static const size_t b74_count = 192;
static const size_t b75_count = 192;
static const size_t b76_count = 192;
static const size_t w20_count = 221184;
static const size_t b77_count = 1152;
static const size_t b78_count = 1152;
static const size_t b79_count = 1152;
static const size_t b80_count = 1152;
static const size_t w21_count = 10368;
static const size_t b81_count = 1152;
static const size_t b82_count = 1152;
static const size_t b83_count = 1152;
static const size_t b84_count = 1152;
static const size_t w22_count = 368640;
static const size_t b85_count = 320;
static const size_t b86_count = 320;
static const size_t b87_count = 320;
static const size_t b88_count = 320;
static const size_t w23_count = 409600;
static const size_t b89_count = 1280;
static const size_t b90_count = 1280;
static const size_t b91_count = 1280;
static const size_t b92_count = 1280;
static const size_t w24_count = 1280000;
static const size_t b93_count = 1000;
static const size_t OUT_COUNT = 10000;

static float *read_floats_at(FILE *f, long byte_offset, size_t n,
                             const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  if (fseek(f, byte_offset, SEEK_SET) != 0) {
    fprintf(stderr, "seek to offset %ld for %s failed\n", byte_offset, what);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s at offset %ld: wanted %zu floats, got "
                    "%zu\n", what, byte_offset, n, got);
    exit(1);
  }
  return p;
}

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void resolve_run_id(int argc, char **argv, char *buf, size_t buflen) {
  if (argc > 5) {
    snprintf(buf, buflen, "%s", argv[5]);
    return;
  }
  time_t now = time(NULL);
  struct tm tm_utc;
  gmtime_r(&now, &tm_utc);
  strftime(buf, buflen, "%Y%m%d_%H%M%S", &tm_utc);
}

static void print_json_string(FILE *f, const char *s) {
  fputc('"', f);
  for (const char *p = s; *p; p++) {
    if (*p == '"' || *p == '\\')
      fputc('\\', f);
    fputc(*p, f);
  }
  fputc('"', f);
}

static void write_timing_report(const char *json_path, const char *model,
                                 const char *pipeline, const char *run_id,
                                 const char *weights_path, const char *input_path,
                                 const char *output_path, int reps,
                                 double median_ns, double mean_ns, double min_ns,
                                 double max_ns) {
  FILE *jf = fopen(json_path, "w");
  if (!jf) {
    fprintf(stderr, "warning: failed to write timing report '%s': ", json_path);
    perror(NULL);
    return;
  }
  fprintf(jf, "{\n  \"model\": ");
  print_json_string(jf, model);
  fprintf(jf, ",\n  \"pipeline\": ");
  print_json_string(jf, pipeline);
  fprintf(jf, ",\n  \"run_id\": ");
  print_json_string(jf, run_id);
  fprintf(jf, ",\n  \"weights_path\": ");
  print_json_string(jf, weights_path);
  fprintf(jf, ",\n  \"input_path\": ");
  print_json_string(jf, input_path);
  fprintf(jf, ",\n  \"output_path\": ");
  print_json_string(jf, output_path);
  fprintf(jf, ",\n  \"reps\": %d", reps);
  fprintf(jf, ",\n  \"median_ns\": %.1f", median_ns);
  fprintf(jf, ",\n  \"mean_ns\": %.1f", mean_ns);
  fprintf(jf, ",\n  \"min_ns\": %.1f", min_ns);
  fprintf(jf, ",\n  \"max_ns\": %.1f", max_ns);
  fprintf(jf, "\n}\n");
  fclose(jf);
  printf("wrote timing report to %s\n", json_path);
  fflush(stdout);
}

/* --- per-call process isolation; see c_fork_helpers() in gen_drivers.py ---
 * Each call to the model runs in a forked child, so the leak of its
 * internal intermediates cannot accumulate across reps. Weights and input
 * are inherited copy-on-write and are NOT duplicated. Elapsed times come
 * back through a shared anonymous mapping, and the final rep's child writes
 * the output file itself so the result never has to cross the process
 * boundary.
 *
 * Set DRIVER_NO_FORK=1 to run every call in-process instead -- the previous
 * behaviour, for A/B or for profilers that dislike fork.
 */
static int driver_fork_enabled(void) {
  const char *e = getenv("DRIVER_NO_FORK");
  return !(e && e[0] && e[0] != '0');
}

static double *alloc_shared_times(int reps) {
  size_t n = (size_t)reps * sizeof(double);
  void *p = mmap(NULL, n, PROT_READ | PROT_WRITE,
                 MAP_SHARED | MAP_ANONYMOUS, -1, 0);
  if (p == MAP_FAILED) {
    perror("mmap for shared timing buffer");
    exit(1);
  }
  return (double *)p;
}

static void await_child(pid_t pid, const char *what) {
  int st = 0;
  if (waitpid(pid, &st, 0) < 0) {
    perror("waitpid");
    exit(1);
  }
  if (WIFSIGNALED(st)) {
    int s = WTERMSIG(st);
    fprintf(stderr, "%s: child killed by signal %d\n", what, s);
    if (s == SIGKILL)
      fprintf(stderr,
              "  SIGKILL almost always means the OOM killer. This model "
              "leaks several GiB\n  per call inside the generated code; a "
              "single call already exceeds free RAM.\n  Forking bounds the "
              "leak to one call, so it cannot help beyond that.\n");
    exit(1);
  }
  if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
    fprintf(stderr, "%s: child exited with status %d\n", what,
            WIFEXITED(st) ? WEXITSTATUS(st) : -1);
    exit(1);
  }
}

static void release_times(double *times, int reps, int forked) {
  if (forked)
    munmap(times, (size_t)reps * sizeof(double));
  else
    free(times);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  char run_id_buf[64];
  resolve_run_id(argc, argv, run_id_buf, sizeof(run_id_buf));
  const char *run_id = run_id_buf;

  char json_path_buf[512];
  const char *json_report_path;
  if (argc > 6) {
    json_report_path = argv[6];
  } else {
    snprintf(json_path_buf, sizeof(json_path_buf), "EfficientNetB1_mim_llvm_%s_timing.json", run_id);
    json_report_path = json_path_buf;
  }

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *w1 = read_floats_at(wf, 0, w1_count, "w1");
  float *b1 = read_floats_at(wf, 3456, b1_count, "b1");
  float *b2 = read_floats_at(wf, 3584, b2_count, "b2");
  float *b3 = read_floats_at(wf, 3712, b3_count, "b3");
  float *b4 = read_floats_at(wf, 3840, b4_count, "b4");
  float *w2 = read_floats_at(wf, 3968, w2_count, "w2");
  float *b5 = read_floats_at(wf, 8064, b5_count, "b5");
  float *b6 = read_floats_at(wf, 8192, b6_count, "b6");
  float *b7 = read_floats_at(wf, 8320, b7_count, "b7");
  float *b8 = read_floats_at(wf, 8448, b8_count, "b8");
  float *w3 = read_floats_at(wf, 8576, w3_count, "w3");
  float *b9 = read_floats_at(wf, 9728, b9_count, "b9");
  float *b10 = read_floats_at(wf, 9856, b10_count, "b10");
  float *b11 = read_floats_at(wf, 9984, b11_count, "b11");
  float *b12 = read_floats_at(wf, 10112, b12_count, "b12");
  float *w4 = read_floats_at(wf, 10240, w4_count, "w4");
  float *b13 = read_floats_at(wf, 12288, b13_count, "b13");
  float *b14 = read_floats_at(wf, 12352, b14_count, "b14");
  float *b15 = read_floats_at(wf, 12416, b15_count, "b15");
  float *b16 = read_floats_at(wf, 12480, b16_count, "b16");
  float *w5 = read_floats_at(wf, 12544, w5_count, "w5");
  float *b17 = read_floats_at(wf, 18688, b17_count, "b17");
  float *b18 = read_floats_at(wf, 19072, b18_count, "b18");
  float *b19 = read_floats_at(wf, 19456, b19_count, "b19");
  float *b20 = read_floats_at(wf, 19840, b20_count, "b20");
  float *w6 = read_floats_at(wf, 20224, w6_count, "w6");
  float *b21 = read_floats_at(wf, 23680, b21_count, "b21");
  float *b22 = read_floats_at(wf, 24064, b22_count, "b22");
  float *b23 = read_floats_at(wf, 24448, b23_count, "b23");
  float *b24 = read_floats_at(wf, 24832, b24_count, "b24");
  float *w7 = read_floats_at(wf, 25216, w7_count, "w7");
  float *b25 = read_floats_at(wf, 34432, b25_count, "b25");
  float *b26 = read_floats_at(wf, 34528, b26_count, "b26");
  float *b27 = read_floats_at(wf, 34624, b27_count, "b27");
  float *b28 = read_floats_at(wf, 34720, b28_count, "b28");
  float *w8 = read_floats_at(wf, 34816, w8_count, "w8");
  float *b29 = read_floats_at(wf, 48640, b29_count, "b29");
  float *b30 = read_floats_at(wf, 49216, b30_count, "b30");
  float *b31 = read_floats_at(wf, 49792, b31_count, "b31");
  float *b32 = read_floats_at(wf, 50368, b32_count, "b32");
  float *w9 = read_floats_at(wf, 50944, w9_count, "w9");
  float *b33 = read_floats_at(wf, 56128, b33_count, "b33");
  float *b34 = read_floats_at(wf, 56704, b34_count, "b34");
  float *b35 = read_floats_at(wf, 57280, b35_count, "b35");
  float *b36 = read_floats_at(wf, 57856, b36_count, "b36");
  float *w10 = read_floats_at(wf, 58432, w10_count, "w10");
  float *b37 = read_floats_at(wf, 81472, b37_count, "b37");
  float *b38 = read_floats_at(wf, 81632, b38_count, "b38");
  float *b39 = read_floats_at(wf, 81792, b39_count, "b39");
  float *b40 = read_floats_at(wf, 81952, b40_count, "b40");
  float *w11 = read_floats_at(wf, 82112, w11_count, "w11");
  float *b41 = read_floats_at(wf, 120512, b41_count, "b41");
  float *b42 = read_floats_at(wf, 121472, b42_count, "b42");
  float *b43 = read_floats_at(wf, 122432, b43_count, "b43");
  float *b44 = read_floats_at(wf, 123392, b44_count, "b44");
  float *w12 = read_floats_at(wf, 124352, w12_count, "w12");
  float *b45 = read_floats_at(wf, 132992, b45_count, "b45");
  float *b46 = read_floats_at(wf, 133952, b46_count, "b46");
  float *b47 = read_floats_at(wf, 134912, b47_count, "b47");
  float *b48 = read_floats_at(wf, 135872, b48_count, "b48");
  float *w13 = read_floats_at(wf, 136832, w13_count, "w13");
  float *b49 = read_floats_at(wf, 213632, b49_count, "b49");
  float *b50 = read_floats_at(wf, 213952, b50_count, "b50");
  float *b51 = read_floats_at(wf, 214272, b51_count, "b51");
  float *b52 = read_floats_at(wf, 214592, b52_count, "b52");
  float *w14 = read_floats_at(wf, 214912, w14_count, "w14");
  float *b53 = read_floats_at(wf, 368512, b53_count, "b53");
  float *b54 = read_floats_at(wf, 370432, b54_count, "b54");
  float *b55 = read_floats_at(wf, 372352, b55_count, "b55");
  float *b56 = read_floats_at(wf, 374272, b56_count, "b56");
  float *w15 = read_floats_at(wf, 376192, w15_count, "w15");
  float *b57 = read_floats_at(wf, 393472, b57_count, "b57");
  float *b58 = read_floats_at(wf, 395392, b58_count, "b58");
  float *b59 = read_floats_at(wf, 397312, b59_count, "b59");
  float *b60 = read_floats_at(wf, 399232, b60_count, "b60");
  float *w16 = read_floats_at(wf, 401152, w16_count, "w16");
  float *b61 = read_floats_at(wf, 616192, b61_count, "b61");
  float *b62 = read_floats_at(wf, 616640, b62_count, "b62");
  float *b63 = read_floats_at(wf, 617088, b63_count, "b63");
  float *b64 = read_floats_at(wf, 617536, b64_count, "b64");
  float *w17 = read_floats_at(wf, 617984, w17_count, "w17");
  float *b65 = read_floats_at(wf, 919040, b65_count, "b65");
  float *b66 = read_floats_at(wf, 921728, b66_count, "b66");
  float *b67 = read_floats_at(wf, 924416, b67_count, "b67");
  float *b68 = read_floats_at(wf, 927104, b68_count, "b68");
  float *w18 = read_floats_at(wf, 929792, w18_count, "w18");
  float *b69 = read_floats_at(wf, 953984, b69_count, "b69");
  float *b70 = read_floats_at(wf, 956672, b70_count, "b70");
  float *b71 = read_floats_at(wf, 959360, b71_count, "b71");
  float *b72 = read_floats_at(wf, 962048, b72_count, "b72");
  float *w19 = read_floats_at(wf, 964736, w19_count, "w19");
  float *b73 = read_floats_at(wf, 1480832, b73_count, "b73");
  float *b74 = read_floats_at(wf, 1481600, b74_count, "b74");
  float *b75 = read_floats_at(wf, 1482368, b75_count, "b75");
  float *b76 = read_floats_at(wf, 1483136, b76_count, "b76");
  float *w20 = read_floats_at(wf, 1483904, w20_count, "w20");
  float *b77 = read_floats_at(wf, 2368640, b77_count, "b77");
  float *b78 = read_floats_at(wf, 2373248, b78_count, "b78");
  float *b79 = read_floats_at(wf, 2377856, b79_count, "b79");
  float *b80 = read_floats_at(wf, 2382464, b80_count, "b80");
  float *w21 = read_floats_at(wf, 2387072, w21_count, "w21");
  float *b81 = read_floats_at(wf, 2428544, b81_count, "b81");
  float *b82 = read_floats_at(wf, 2433152, b82_count, "b82");
  float *b83 = read_floats_at(wf, 2437760, b83_count, "b83");
  float *b84 = read_floats_at(wf, 2442368, b84_count, "b84");
  float *w22 = read_floats_at(wf, 2446976, w22_count, "w22");
  float *b85 = read_floats_at(wf, 3921536, b85_count, "b85");
  float *b86 = read_floats_at(wf, 3922816, b86_count, "b86");
  float *b87 = read_floats_at(wf, 3924096, b87_count, "b87");
  float *b88 = read_floats_at(wf, 3925376, b88_count, "b88");
  float *w23 = read_floats_at(wf, 3926656, w23_count, "w23");
  float *b89 = read_floats_at(wf, 5565056, b89_count, "b89");
  float *b90 = read_floats_at(wf, 5570176, b90_count, "b90");
  float *b91 = read_floats_at(wf, 5575296, b91_count, "b91");
  float *b92 = read_floats_at(wf, 5580416, b92_count, "b92");
  float *w24 = read_floats_at(wf, 5585536, w24_count, "w24");
  float *b93 = read_floats_at(wf, 10705536, b93_count, "b93");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  const int use_fork = driver_fork_enabled();
  double *times = use_fork ? alloc_shared_times(reps)
                           : (double *)malloc(reps * sizeof(double));
  printf("call isolation: %s\n", use_fork ? "fork per call" : "in-process (DRIVER_NO_FORK)");

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  if (use_fork) {
    fflush(NULL);
    pid_t p = fork();
    if (p < 0) { perror("fork"); return 1; }
    if (p == 0) {
      float *out = EfficientNetB1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93);
      free(out);
      _exit(0);
    }
    await_child(p, "warm-up");
  } else {
    float *out = EfficientNetB1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    const int is_last = (i == reps - 1);
    if (use_fork) {
      fflush(NULL);
      pid_t p = fork();
      if (p < 0) { perror("fork"); return 1; }
      if (p == 0) {
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        float *cur = EfficientNetB1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93);
        clock_gettime(CLOCK_MONOTONIC, &t1);
        times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                   (double)(t1.tv_nsec - t0.tv_nsec);
        /* The last rep's child owns writing the result -- that keeps the
           output buffer from having to cross the process boundary.
           write_result() frees `cur`. */
        if (is_last)
          write_result(cur, output_path);
        _exit(0);
      }
      await_child(p, "timed rep");
    } else {
      struct timespec t0, t1;
      clock_gettime(CLOCK_MONOTONIC, &t0);
      float *cur = EfficientNetB1(w1, x, b1, b2, b3, b4, w2, b5, b6, b7, b8, w3, b9, b10, b11, b12, w4, b13, b14, b15, b16, w5, b17, b18, b19, b20, w6, b21, b22, b23, b24, w7, b25, b26, b27, b28, w8, b29, b30, b31, b32, w9, b33, b34, b35, b36, w10, b37, b38, b39, b40, w11, b41, b42, b43, b44, w12, b45, b46, b47, b48, w13, b49, b50, b51, b52, w14, b53, b54, b55, b56, w15, b57, b58, b59, b60, w16, b61, b62, b63, b64, w17, b65, b66, b67, b68, w18, b69, b70, b71, b72, w19, b73, b74, b75, b76, w20, b77, b78, b79, b80, w21, b81, b82, b83, b84, w22, b85, b86, b87, b88, w23, b89, b90, b91, b92, w24, b93);
      clock_gettime(CLOCK_MONOTONIC, &t1);
      times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
                 (double)(t1.tv_nsec - t0.tv_nsec);
      if (out)
        free(out);
      out = cur;
    }
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  if (!use_fork)
    write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  write_timing_report(json_report_path, "EfficientNetB1", "mim_llvm", run_id,
                       weights_path, input_path, output_path, reps,
                       times[reps / 2], sum / reps, times[0], times[reps - 1]);

  free(x);
  release_times(times, reps, use_fork);
  return 0;
}
