#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/* Auto-generated driver for `DeepNarrowMLP` ("mim" raw-pointer calling convention).
 * Generated by gen_drivers.py -- do not hand-edit.
 *
 * Parameter shapes (in declaration order):
 * x: shape [1024, 8192] (input)
 * b1: shape [1024] (bias)
 * w1: shape [1024, 8192] (weight)
 * w2: shape [1024, 1024] (weight)
 * b2: shape [1024] (bias)
 * w3: shape [1024, 1024] (weight)
 * b3: shape [1024] (bias)
 * w4: shape [1024, 1024] (weight)
 * b4: shape [1024] (bias)
 * w5: shape [1024, 1024] (weight)
 * b5: shape [1024] (bias)
 * w6: shape [1024, 1024] (weight)
 * b6: shape [1024] (bias)
 * w7: shape [1024, 1024] (weight)
 * b7: shape [1024] (bias)
 * w8: shape [1024, 1024] (weight)
 * b8: shape [1024] (bias)
 * w9: shape [1024, 1024] (weight)
 * b9: shape [1024] (bias)
 * w10: shape [1024, 1024] (weight)
 * b10: shape [1024] (bias)
 * w11: shape [1024, 1024] (weight)
 * b11: shape [1024] (bias)
 * w12: shape [1024, 1024] (weight)
 * b12: shape [1024] (bias)
 * w13: shape [1024, 1024] (weight)
 * b13: shape [1024] (bias)
 * w14: shape [1024, 1024] (weight)
 * b14: shape [1024] (bias)
 * w15: shape [1024, 1024] (weight)
 * b15: shape [1024] (bias)
 * w16: shape [1024, 1024] (weight)
 * b16: shape [1024] (bias)
 * w17: shape [8192, 1024] (weight)
 * b17: shape [8192] (bias)
 * output: shape [1024, 8192]
 *
 * The LLVM signature may declare this as a single struct-of-pointers
 * argument or as separate pointer arguments -- either way the SysV x86-64
 * ABI (for a non-`byval` aggregate, or for separate scalar pointer args)
 * flattens it into one pointer per calling-convention slot in order, so a
 * flat `float *` extern declaration reproduces the real calling convention
 * with no translation layer.
 */
extern float *DeepNarrowMLP(float *x, float *b1, float *w1, float *w2, float *b2, float *w3, float *b3, float *w4, float *b4, float *w5, float *b5, float *w6, float *b6, float *w7, float *b7, float *w8, float *b8, float *w9, float *b9, float *w10, float *b10, float *w11, float *b11, float *w12, float *b12, float *w13, float *b13, float *w14, float *b14, float *w15, float *b15, float *w16, float *b16, float *w17, float *b17);

static const size_t x_count = 8388608;
static const size_t b1_count = 1024;
static const size_t w1_count = 8388608;
static const size_t w2_count = 1048576;
static const size_t b2_count = 1024;
static const size_t w3_count = 1048576;
static const size_t b3_count = 1024;
static const size_t w4_count = 1048576;
static const size_t b4_count = 1024;
static const size_t w5_count = 1048576;
static const size_t b5_count = 1024;
static const size_t w6_count = 1048576;
static const size_t b6_count = 1024;
static const size_t w7_count = 1048576;
static const size_t b7_count = 1024;
static const size_t w8_count = 1048576;
static const size_t b8_count = 1024;
static const size_t w9_count = 1048576;
static const size_t b9_count = 1024;
static const size_t w10_count = 1048576;
static const size_t b10_count = 1024;
static const size_t w11_count = 1048576;
static const size_t b11_count = 1024;
static const size_t w12_count = 1048576;
static const size_t b12_count = 1024;
static const size_t w13_count = 1048576;
static const size_t b13_count = 1024;
static const size_t w14_count = 1048576;
static const size_t b14_count = 1024;
static const size_t w15_count = 1048576;
static const size_t b15_count = 1024;
static const size_t w16_count = 1048576;
static const size_t b16_count = 1024;
static const size_t w17_count = 8388608;
static const size_t b17_count = 8192;
static const size_t OUT_COUNT = 8388608;

static float *read_floats(FILE *f, size_t n, const char *what) {
  float *p = (float *)malloc(n * sizeof(float));
  if (!p) {
    fprintf(stderr, "out of memory reading %s (%zu floats)\n", what, n);
    exit(1);
  }
  size_t got = fread(p, sizeof(float), n, f);
  if (got != n) {
    fprintf(stderr, "short read on %s: wanted %zu floats, got %zu\n", what, n,
            got);
    exit(1);
  }
  return p;
}

static int cmp_double(const void *a, const void *b) {
  double x = *(const double *)a, y = *(const double *)b;
  return (x > y) - (x < y);
}

static void write_result(float *out, const char *output_path) {
  printf("writing output to %s...\n", output_path);
  fflush(stdout);
  FILE *of = fopen(output_path, "wb");
  if (!of) {
    fprintf(stderr, "failed to open output file '%s': ", output_path);
    perror(NULL);
    exit(1);
  }
  size_t wrote = fwrite(out, sizeof(float), OUT_COUNT, of);
  fclose(of);
  if (wrote != OUT_COUNT) {
    fprintf(stderr, "short write on output: wanted %zu floats, wrote %zu\n",
            OUT_COUNT, wrote);
    exit(1);
  }
  free(out);
}

int main(int argc, char **argv) {
  printf("reading weights...\n");
  fflush(stdout);
  const char *weights_path = argc > 1 ? argv[1] : "weights.bin";
  const char *input_path = argc > 2 ? argv[2] : "input.bin";
  int reps = argc > 3 ? atoi(argv[3]) : 5;
  const char *output_path = argc > 4 ? argv[4] : "output_mim.bin";

  FILE *wf = fopen(weights_path, "rb");
  if (!wf) {
    fprintf(stderr, "failed to open weights file '%s': ", weights_path);
    perror(NULL);
    return 1;
  }

  float *b1 = read_floats(wf, b1_count, "b1");
  float *w1 = read_floats(wf, w1_count, "w1");
  float *w2 = read_floats(wf, w2_count, "w2");
  float *b2 = read_floats(wf, b2_count, "b2");
  float *w3 = read_floats(wf, w3_count, "w3");
  float *b3 = read_floats(wf, b3_count, "b3");
  float *w4 = read_floats(wf, w4_count, "w4");
  float *b4 = read_floats(wf, b4_count, "b4");
  float *w5 = read_floats(wf, w5_count, "w5");
  float *b5 = read_floats(wf, b5_count, "b5");
  float *w6 = read_floats(wf, w6_count, "w6");
  float *b6 = read_floats(wf, b6_count, "b6");
  float *w7 = read_floats(wf, w7_count, "w7");
  float *b7 = read_floats(wf, b7_count, "b7");
  float *w8 = read_floats(wf, w8_count, "w8");
  float *b8 = read_floats(wf, b8_count, "b8");
  float *w9 = read_floats(wf, w9_count, "w9");
  float *b9 = read_floats(wf, b9_count, "b9");
  float *w10 = read_floats(wf, w10_count, "w10");
  float *b10 = read_floats(wf, b10_count, "b10");
  float *w11 = read_floats(wf, w11_count, "w11");
  float *b11 = read_floats(wf, b11_count, "b11");
  float *w12 = read_floats(wf, w12_count, "w12");
  float *b12 = read_floats(wf, b12_count, "b12");
  float *w13 = read_floats(wf, w13_count, "w13");
  float *b13 = read_floats(wf, b13_count, "b13");
  float *w14 = read_floats(wf, w14_count, "w14");
  float *b14 = read_floats(wf, b14_count, "b14");
  float *w15 = read_floats(wf, w15_count, "w15");
  float *b15 = read_floats(wf, b15_count, "b15");
  float *w16 = read_floats(wf, w16_count, "w16");
  float *b16 = read_floats(wf, b16_count, "b16");
  float *w17 = read_floats(wf, w17_count, "w17");
  float *b17 = read_floats(wf, b17_count, "b17");
  fclose(wf);

  printf("weights loaded.\n");
  fflush(stdout);

  printf("reading input...\n");
  fflush(stdout);
  FILE *xf = fopen(input_path, "rb");
  if (!xf) {
    fprintf(stderr, "failed to open input file '%s': ", input_path);
    perror(NULL);
    return 1;
  }
  float *x = read_floats(xf, x_count, "x");
  fclose(xf);

  printf("input loaded.\n");
  fflush(stdout);
  double *times = (double *)malloc(reps * sizeof(double));

  printf("start warm-up (1 call)...\n");
  fflush(stdout);
  for (int i = 0; i < 1; i++) {
    float *out = DeepNarrowMLP(x, b1, w1, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16, w17, b17);
    free(out);
  }
  printf("warm-up done.\n");
  fflush(stdout);
  printf("start timed reps...\n");
  fflush(stdout);
  float *out = NULL;
  for (int i = 0; i < reps; i++) {
    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    float *cur = DeepNarrowMLP(x, b1, w1, w2, b2, w3, b3, w4, b4, w5, b5, w6, b6, w7, b7, w8, b8, w9, b9, w10, b10, w11, b11, w12, b12, w13, b13, w14, b14, w15, b15, w16, b16, w17, b17);
    clock_gettime(CLOCK_MONOTONIC, &t1);
    times[i] = (double)(t1.tv_sec - t0.tv_sec) * 1e9 +
               (double)(t1.tv_nsec - t0.tv_nsec);
    if (out)
      free(out);
    out = cur;
  }
  printf("finish timed reps...\n");
  fflush(stdout);

  write_result(out, output_path);

  qsort(times, reps, sizeof(double), cmp_double);
  double sum = 0;
  for (int i = 0; i < reps; i++)
    sum += times[i];

  printf("pipeline=mim->llvm weights=%s input=%s reps=%d median_ns=%.1f "
         "mean_ns=%.1f min_ns=%.1f max_ns=%.1f\n",
         weights_path, input_path, reps, times[reps / 2], sum / reps, times[0],
         times[reps - 1]);

  free(x);
  free(times);
  return 0;
}
